//
// SFAccountZoneUsage.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"

@class SFZone;

@interface SFAccountZoneUsage : SFODataObject
{
}

@property (nonatomic, strong) NSNumber *TotalFileSizeBytes;
@property (nonatomic, strong) SFZone *Zone;
@property (nonatomic, strong) NSNumber *RootFolderCount;
@property (nonatomic, strong) NSNumber *FileCount;


@end
