//
// SFAccessControlBulkResult.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFAccessControlBulkResult : SFODataObject
{
}

/**
   A list of entities processed successfully
 */
@property (nonatomic, strong) NSArray *SuccessEntities;
/**
   A list of entities for which the operation failed
 */
@property (nonatomic, strong) NSArray *FailedEntities;


@end
