//
// SFAccessControlsBulkParams.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFAccessControlsBulkParams : SFODataObject
{
}

/**
   Defines whether the principal should receieve a notice on the permission grant.
   If an AccessControlParam doesn't specify the property it is inherited from here.
 */
@property (nonatomic, strong) NSNumber *NotifyUser;
/**
   Custom notification message, if any
   If an AccessControlParam doesn't specify the property it is inherited from here.
 */
@property (nonatomic, strong) NSString *NotifyMessage;
/**
   AccessControlParams
 */
@property (nonatomic, strong) NSArray *AccessControlParams;


@end
