//
// SFAccountPreferences.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFAccountPreferences.h"
#import "SFODataObject.h"

@class SFZone;
@class SFAccountMessageCode;

@implementation SFAccountPreferences

@end
