//
// SFAccount.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFAccount.h"
#import "SFODataObject.h"

@class SFUser;
@class SFUserUsage;
@class SFDiskSpace;
@class SFItem;
@class SFSSOAccountProvider;
@class SFAccountPreferences;
@class SFProductDefaults;
@class SFMobileSecuritySettings;
@class SFAccessControlDomains;
@class SFBillingInfo;
@class SFServicesCollection;

@implementation SFAccount

@end
