//
// SFAccessControl.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFAccessControl.h"
#import "SFODataObject.h"

@class SFItem;
@class SFPrincipal;

@implementation SFAccessControl

@end
