//
// SFAccessControl.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"

@class SFItem;
@class SFPrincipal;

@interface SFAccessControl : SFODataObject
{
}

/**
   Item that was given permission through this rule
 */
@property (nonatomic, strong) SFItem *Item;
@property (nonatomic, strong) SFPrincipal *Principal;
/**
   Defines whether the principal can add files (upload) into the Item
 */
@property (nonatomic, strong) NSNumber *CanUpload;
/**
   Defines whether the principal can read file content (download) from this Item
 */
@property (nonatomic, strong) NSNumber *CanDownload;
/**
   Defines whether the principal can view items (browse) from this Item
 */
@property (nonatomic, strong) NSNumber *CanView;
/**
   Defines whether the principal can remove items from this Item
 */
@property (nonatomic, strong) NSNumber *CanDelete;
/**
   Defines whether the principal can configure Access Controls in this Item
 */
@property (nonatomic, strong) NSNumber *CanManagePermissions;
/**
   Defines the notification preference for upload events. If set, the principal will receive
   notifications when new files are uploaded into this Item
 */
@property (nonatomic, strong) NSNumber *NotifyOnUpload;
/**
   Defines the notification preference for download events. If set, the principal will receive
   notifiation when items are downloaded from this Item.
 */
@property (nonatomic, strong) NSNumber *NotifyOnDownload;
/**
   Defines whether the principal is the owner of this Item
 */
@property (nonatomic, strong) NSNumber *IsOwner;


@end
