//
// SFAccessControlFailedEntry.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFAccessControlFailedEntry.h"
#import "SFODataObject.h"

@class SFAccessControl;
@class SFODataExceptionMessage;

@implementation SFAccessControlFailedEntry

@end
