//
// SFADevice.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFADevice.h"
#import "SFODataObject.h"

@class SFUser;

@implementation SFADevice

@end
