//
// SFAsyncOperation.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFAsyncOperation.h"
#import "SFODataObject.h"

@class SFAccount;
@class SFZone;
@class SFItem;
@class SFUser;

@implementation SFAsyncOperation

@end
