//
// SFASession.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFASession.h"
#import "SFODataObject.h"

@class SFPrincipal;
@class SFDeviceUser;

@implementation SFASession

@end
