//
// SFCapability.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFCapability : SFODataObject
{
}

@property (nonatomic, strong) NSString *Name;
@property (nonatomic, strong) NSString *Version;


@end
