//
// SFCapability.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFCapability.h"
#import "SFODataObject.h"


@implementation SFCapability

@end
