//
// SFConnectorGroup.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFFolder.h"
#import "SFODataObject.h"


@interface SFConnectorGroup : SFFolder
{
}

/**
   Zones that contain this Connector type
 */
@property (nonatomic, strong) NSArray *Zones;
/**
   Provider identifier for this group. This is the 1st element in a ShareFile URL,
   for example - cifs for Network Shares connectors. Items in Network Share connectors
   will always have the url /cifs/vN/...
 */
@property (nonatomic, strong) NSString *Provider;


@end
