//
// SFContact.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFContact.h"
#import "SFPrincipal.h"
#import "SFODataObject.h"

@class SFUser;

@implementation SFContact

@end
