//
// SFDeviceStatus.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFDeviceStatus : SFODataObject
{
}

/**
   Locked users
 */
@property (nonatomic, strong) NSArray *LockedUsers;
/**
   Users to wipe
 */
@property (nonatomic, strong) NSArray *UsersToWipe;


@end
