//
// SFDeviceUser.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFDeviceUser.h"
#import "SFODataObject.h"

@class SFAccount;
@class SFUser;
@class SFADevice;

@implementation SFDeviceUser

@end
