//
// SFDeviceUser.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"

@class SFAccount;
@class SFUser;
@class SFDevice;

@interface SFDeviceUser : SFODataObject
{
}

@property (nonatomic, strong) SFAccount *Account;
@property (nonatomic, strong) SFUser *User;
@property (nonatomic, strong) SFDevice *Device;
@property (nonatomic, strong) NSNumber *IsOwner;
@property (nonatomic, strong) NSString *FriendlyName;
@property (nonatomic, strong) NSNumber *Wipe;
@property (nonatomic, strong) NSNumber *IsLocked;
@property (nonatomic, strong) NSNumber *IsDeleted;
@property (nonatomic, strong) NSDate *Created;
@property (nonatomic, strong) NSDate *LastLogin;
@property (nonatomic, strong) NSDate *LastWipe;
@property (nonatomic, strong) NSString *WipeToken;
@property (nonatomic, strong) NSString *WipeInitiator;
@property (nonatomic, strong) NSString *WipeInitiatorRole;
@property (nonatomic, strong) NSString *LockInitiator;
@property (nonatomic, strong) NSString *LockInitiatorRole;
@property (nonatomic, strong) NSString *DeviceType;
@property (nonatomic, strong) NSString *LastErrorMessage;


@end
