//
// SFDevice.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"

@class SFUser;

@interface SFDevice : SFODataObject
{
}

@property (nonatomic, strong) NSString *Tool;
@property (nonatomic, strong) NSString *ToolRaw;
@property (nonatomic, strong) SFUser *Owner;
@property (nonatomic, strong) NSDate *Created;
@property (nonatomic, strong) NSString *ToolVersion;
@property (nonatomic, strong) NSNumber *JustRegistered;
@property (nonatomic, strong) NSNumber *IsRemoteWipeReady;


@end
