//
// SFDiskSpace.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFDiskSpace : SFODataObject
{
}

@property (nonatomic, strong) NSNumber *Max;
@property (nonatomic, strong) NSNumber *Used;
@property (nonatomic, strong) NSNumber *Free;


@end
