//
// SFDiskSpace.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFDiskSpace.h"
#import "SFODataObject.h"


@implementation SFDiskSpace

@end
