//
// SFDownloadSpecification.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFDownloadSpecification : SFODataObject
{
}

@property (nonatomic, strong) NSString *DownloadToken;
@property (nonatomic, strong) NSString *PrepareXmlInfo;
@property (nonatomic, strong) NSURL *DownloadUrl;
@property (nonatomic, strong) NSURL *DownloadPrepStartURL;
@property (nonatomic, strong) NSURL *DownloadPrepStatusURL;


@end
