//
// SFEditingPlatformInfo.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"

@class SFItemProtocolLink;

@interface SFEditingPlatformInfo : SFODataObject
{
}

@property (nonatomic, strong) NSString *EditingPlatform;
@property (nonatomic, strong) SFItemProtocolLink *ItemProtocolLink;


@end
