//
// SFEditingPlatformInfo.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFEditingPlatformInfo.h"
#import "SFODataObject.h"

@class SFItemProtocolLink;

@implementation SFEditingPlatformInfo

@end
