//
// SFEnsSubscriptionRequest.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"

@class SFODataObject;

@interface SFEnsSubscriptionRequest : SFODataObject
{
}

@property (nonatomic, strong) NSString *EnsServerUrl;
@property (nonatomic, strong) NSString *ClientId;
@property (nonatomic, strong) SFODataObject *Entity;
@property (nonatomic, strong) NSString *EventTypes;
@property (nonatomic, strong) NSNumber *IncludeProgeny;


@end
