//
// SFEnsSubscriptionToken.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFEnsSubscriptionToken : SFODataObject
{
}

@property (nonatomic, strong) NSString *SubscriptionId;
@property (nonatomic, strong) NSString *EntityId;
@property (nonatomic, strong) NSString *EventTypes;
@property (nonatomic, strong) NSNumber *IncludeProgeny;
@property (nonatomic, strong) NSNumber *LastEventCount;


@end
