//
// SFEnsSubscriptionRequest.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFEnsSubscriptionRequest.h"
#import "SFODataObject.h"

@class SFODataObject;

@implementation SFEnsSubscriptionRequest

@end
