//
// SFESignature.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFESignature : SFODataObject
{
}

@property (nonatomic, strong) NSString *ID;
@property (nonatomic, strong) NSString *ItemID;
@property (nonatomic, strong) NSString *ReferenceID;
@property (nonatomic, strong) NSString *AlternateReferenceID;
@property (nonatomic, strong) NSString *SignedItemID;
@property (nonatomic, strong) NSString *Provider;
@property (nonatomic, strong) NSString *UserID;
@property (nonatomic, strong) NSString *Status;
@property (nonatomic, strong) NSDate *DateCreated;
@property (nonatomic, strong) NSDate *DateLastUpdated;
@property (nonatomic, strong) NSString *DocumentUrl;


@end
