//
// SFFavoriteFolder.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFFavoriteFolder.h"
#import "SFODataObject.h"

@class SFUser;
@class SFItem;

@implementation SFFavoriteFolder

@end
