//
// SFFile.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFFile.h"
#import "SFItem.h"
#import "SFODataObject.h"

@class SFItemDlpInfo;
@class SFItemInfo;
@class SFUser;
@class SFFileLock;
@class SFESignature;

@implementation SFFile

@end
