//
// SFFileLock.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFFileLock.h"
#import "SFODataObject.h"

@class SFPrincipal;

@implementation SFFileLock

@end
