//
// SFFileLock.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"

@class SFPrincipal;

@interface SFFileLock : SFODataObject
{
}

@property (nonatomic, strong) NSString *LockId;
@property (nonatomic, strong) NSString *LockType;
@property (nonatomic, strong) SFPrincipal *Owner;
@property (nonatomic, strong) NSNumber *ExpirationTimeInMinutes;


@end
