//
// SFFindSubdomainResult.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFFindSubdomainResult : SFODataObject
{
}

@property (nonatomic, strong) NSString *UserID;
@property (nonatomic, strong) NSString *Email;
@property (nonatomic, strong) NSString *AccountID;
@property (nonatomic, strong) NSString *CompanyName;
@property (nonatomic, strong) NSString *Subdomain;


@end
