//
// SFFindSubdomainResult.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFFindSubdomainResult.h"
#import "SFODataObject.h"


@implementation SFFindSubdomainResult

@end
