//
// SFFindSubdomainParams.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFFindSubdomainParams : SFODataObject
{
}

@property (nonatomic, strong) NSString *UsernameShort;
@property (nonatomic, strong) NSString *Password;
@property (nonatomic, strong) NSNumber *EmployeeOnly;


@end
