//
// SFFolder.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFFolder.h"

@class SFItemInfo;
@class SFRedirection;
@class SFFavoriteFolder;

@implementation SFFolder

@end
