//
// SFFolderTemplate.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"

@class SFUser;

@interface SFFolderTemplate : SFODataObject
{
}

@property (nonatomic, strong) NSString *Name;
@property (nonatomic, strong) NSString *Description;
@property (nonatomic, strong) SFUser *Creator;
@property (nonatomic, strong) NSArray *Items;


@end
