//
// SFFolderTemplateItem.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFFolderTemplateItem.h"
#import "SFODataObject.h"


@implementation SFFolderTemplateItem

@end
