//
// SFGroup.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFGroup.h"
#import "SFPrincipal.h"
#import "SFODataObject.h"

@class SFUser;
@class SFAccount;

@implementation SFGroup

@end
