//
// SFGroup.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFPrincipal.h"
#import "SFODataObject.h"

@class SFUser;
@class SFAccount;

@interface SFGroup : SFPrincipal
{
}

@property (nonatomic, strong) SFUser *Owner;
@property (nonatomic, strong) SFAccount *Account;
@property (nonatomic, strong) NSNumber *IsShared;
@property (nonatomic, strong) NSArray *Contacts;


@end
