//
// SFIAccessControlsCloneParams.h
// 
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIAccessControlsCloneParams : SFIODataObject
{

}

/**
Defines whether the cloned principals should receieve a notice on the permission grant.
*/
@property (nonatomic, strong) NSNumber *NotifyUser;
/**
Custom notification message, if any.
*/
@property (nonatomic, strong) NSString *NotifyMessage;
/**
The source principal's permissions for this folder and all subdirectories
will be copied into the cloned users.
*/
@property (nonatomic, strong) NSString *FolderId;
/**
This principal's permissions will be used as the source for all cloned users.
*/
@property (nonatomic, strong) NSString *PrincipalId;
/**
List of existing principals that will receive cloned permissions.
*/
@property (nonatomic, strong) NSArray *ClonePrincipalIds;


@end
