//
// SFIAccountUser.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIAccountUser.h"
#import "SFIUser.h"
#import "SFIODataObject.h"


@implementation SFIAccountUser

@end
