//
// SFIAsyncOperation.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"

@class SFIAccount;
@class SFIZone;
@class SFIItem;
@class SFIUser;

@interface SFIAsyncOperation : SFIODataObject
{
}

/**
   Operation type
 */
@property (nonatomic, strong) NSString *Operation;
/**
   ShareFile Account
 */
@property (nonatomic, strong) SFIAccount *Account;
/**
   Represents the Zone that is driving the asynchronous operation process. It
   may be null if the operation is driven by the control plane.
 */
@property (nonatomic, strong) SFIZone *AuthorityZone;
/**
   Source Item for the operation.
 */
@property (nonatomic, strong) SFIItem *Source;
/**
   User that initiated the operation
 */
@property (nonatomic, strong) SFIUser *User;
/**
   Operation creation date
 */
@property (nonatomic, strong) NSDate *CreationDate;
/**
   Operation state. States 'Created' and 'Scheduled' indicate the operation is
   in progress; States 'Success' and 'Failure' indicate the operatoin is finalized
 */
@property (nonatomic, strong) NSString *State;
/**
   Last time the operation state was modified
 */
@property (nonatomic, strong) NSDate *UpdateDate;
/**
   Target Item for the operation.
 */
@property (nonatomic, strong) SFIItem *Target;
/**
   Batch Identifier for an asynchronous operation that includes multiple Items - for
   example, a recursive Copy will create a single AsyncOp instance per file, all sharing
   the same BatchID
 */
@property (nonatomic, strong) NSString *BatchID;
/**
   Item ID used as source for the Batch operation
 */
@property (nonatomic, strong) NSString *BatchSourceID;
/**
   Item ID used as target for the Batch operation
 */
@property (nonatomic, strong) NSString *BatchTargetID;
/**
   BatchProgress indicates the progress of the Batch operation
 */
@property (nonatomic, strong) NSNumber *BatchProgress;
/**
   Batch Operation state. State 'Scheduled' indicate the operation is
   in progress; States 'Success' and 'Failure' indicate the operation is finalized
 */
@property (nonatomic, strong) NSString *BatchState;
@property (nonatomic, strong) NSNumber *BatchTotal;


@end
