//
// SFIAccountPreferences.h
// 
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"

@class SFIZone;
@class SFIAccountMessageCode;

@interface SFIAccountPreferences : SFIODataObject
{

}

@property (nonatomic, strong) NSNumber *EnableViewOnly;
@property (nonatomic, strong) NSNumber *EnableWatermarkOnViewOnly;
@property (nonatomic, strong) NSNumber *AllowProactiveNotifications;
@property (nonatomic, strong) NSNumber *ShowUserListToClients;
@property (nonatomic, strong) NSNumber *RequireLoginOnDownload;
@property (nonatomic, strong) NSNumber *RequireLoginByDefault;
@property (nonatomic, strong) NSNumber *EnableClientSend;
@property (nonatomic, strong) NSNumber *EnableThumbnails;
@property (nonatomic, strong) NSNumber *EnableSSO;
@property (nonatomic, strong) NSNumber *VirusStrictness;
@property (nonatomic, strong) NSNumber *EnableSfAdi;
@property (nonatomic, strong) NSNumber *EnableMultipleZones;
@property (nonatomic, strong) SFIZone *DefaultZone;
@property (nonatomic, strong) NSNumber *EnableVersioning;
@property (nonatomic, strong) NSString *SystemType;
@property (nonatomic, strong) NSNumber *EnableSync;
@property (nonatomic, strong) NSNumber *EnableSyncAutoUpdate;
@property (nonatomic, strong) NSString *SystemName;
@property (nonatomic, strong) NSString *HomeScreenName;
@property (nonatomic, strong) NSNumber *ShowTermsCheckbox;
@property (nonatomic, strong) NSString *TermsCheckboxText;
@property (nonatomic, strong) NSNumber *TermsCheckboxStrictness;
@property (nonatomic, strong) NSNumber *RequireCompanyNameWithUserInfo;
@property (nonatomic, strong) NSNumber *EnableEditor;
@property (nonatomic, strong) NSNumber *ShareIDMaxExpirationDays;
@property (nonatomic, strong) NSNumber *AdminIsSuperUser;
@property (nonatomic, strong) NSNumber *ShowFolderAccessList;
@property (nonatomic, strong) NSNumber *FromEmailIsShareFile;
@property (nonatomic, strong) NSNumber *UseAlternateSMTP;
@property (nonatomic, strong) NSNumber *ShowPasswordInEmail;
@property (nonatomic, strong) NSString *EmailPasswordText;
@property (nonatomic, strong) NSNumber *EnableSelfNotificationsUpload;
@property (nonatomic, strong) NSNumber *EnableSelfNotificationsDownload;
@property (nonatomic, strong) NSNumber *EnableUploadShareIDReceipt;
@property (nonatomic, strong) NSNumber *DefaultConsolidatedNotificationInterval;
@property (nonatomic, strong) NSNumber *ExpirationDays;
@property (nonatomic, strong) NSString *DefaultSortField;
@property (nonatomic, strong) NSString *DefaultSortOrder;
@property (nonatomic, strong) NSNumber *DefaultIsVersioned;
@property (nonatomic, strong) NSNumber *DefaultMaxVersions;
@property (nonatomic, strong) NSString *ViewOnlyWatermarkText;
@property (nonatomic, strong) NSNumber *EnableDocViewerPrinting;
@property (nonatomic, strong) NSNumber *EnableWatermarkedDownloads;
@property (nonatomic, strong) NSNumber *EnableTwoFactorAuth;
@property (nonatomic, strong) NSNumber *LoginFailMaxAttempts;
@property (nonatomic, strong) NSNumber *LoginFailLockoutSecs;
@property (nonatomic, strong) NSString *IPRestrictions;
@property (nonatomic, strong) NSNumber *InactiveTimeoutMins;
@property (nonatomic, strong) NSNumber *OAuth2RefreshTokenLifetimeMinutes;
@property (nonatomic, strong) NSString *PasswordRegEx;
@property (nonatomic, strong) NSString *PasswordRegExFormula;
@property (nonatomic, strong) NSString *PasswordRegExDescription;
@property (nonatomic, strong) NSNumber *EnableActivationLinks;
@property (nonatomic, strong) NSNumber *IsFINRA;
@property (nonatomic, strong) NSNumber *EnableOAuth;
@property (nonatomic, strong) NSNumber *EnableQandA;
@property (nonatomic, strong) NSNumber *EnableQandATextInNotifications;
@property (nonatomic, strong) NSString *UXMode;
@property (nonatomic, strong) NSNumber *IndustryCode;
@property (nonatomic, strong) NSNumber *PasswordMaxAgeDays;
@property (nonatomic, strong) NSNumber *PasswordHistoryCount;
@property (nonatomic, strong) NSNumber *MinimumLength;
@property (nonatomic, strong) NSNumber *MinimumSpecialCharacters;
@property (nonatomic, strong) NSNumber *MinimumNumeric;
@property (nonatomic, strong) NSString *AllowedSpecialCharacters;
@property (nonatomic, strong) NSNumber *EnableWebDAV;
@property (nonatomic, strong) NSString *WebDAVServerName;
@property (nonatomic, strong) NSNumber *EnableFTP;
@property (nonatomic, strong) NSNumber *EnableSFTP;
@property (nonatomic, strong) NSString *FtpServerName;
@property (nonatomic, strong) NSNumber *DisableMarketing;
@property (nonatomic, strong) NSString *VDRDocViewerURL;
@property (nonatomic, strong) NSNumber *EnableSMBConnectorForAccount;
@property (nonatomic, strong) NSNumber *EnablePersonalCloudConnectors;
@property (nonatomic, strong) NSString *AccountID;
@property (nonatomic, strong) NSNumber *EnableStorageZoneConnector;
@property (nonatomic, strong) NSNumber *HasAnyConnectorZones;
@property (nonatomic, strong) NSNumber *EnableENSForAccount;
@property (nonatomic, strong) NSString *ENSRecommendedPollingSyncInterval;
@property (nonatomic, strong) NSString *ENSRecommendedNotificationSyncInterval;
@property (nonatomic, strong) NSNumber *ENSNotificationConfigurationCount;
@property (nonatomic, strong) NSNumber *ENSFailSafePollingCount;
@property (nonatomic, strong) NSNumber *ENSMaxNotificationSyncWaitCount;
@property (nonatomic, strong) NSString *TrustedDomains;
@property (nonatomic, strong) NSNumber *UseWebPopAsWebAppLogin;
@property (nonatomic, strong) NSNumber *EnableReportingV3;
@property (nonatomic, strong) NSNumber *EnableEncryptedEmailForOutlookPlugin;
@property (nonatomic, strong) NSNumber *EnableDocPreviews;
@property (nonatomic, strong) NSNumber *DisablePasswordAutocompleteInWebApp;
@property (nonatomic, strong) NSNumber *EnableDesktopEditorForAccount;
@property (nonatomic, strong) NSNumber *UseStrictEmployeeDefinition;
@property (nonatomic, strong) NSString *EmployeeEmailDomains;
@property (nonatomic, strong) NSNumber *IsPremier;
@property (nonatomic, strong) NSNumber *DisableShareConnectForAccount;
@property (nonatomic, strong) NSNumber *DisablePrintToShareFile;
@property (nonatomic, strong) NSNumber *EnableWebAppConnectorBrowsing;
@property (nonatomic, strong) NSNumber *EnableStrictCrossdomainPolicy;
@property (nonatomic, strong) NSNumber *DisableScanSnap;
@property (nonatomic, strong) NSNumber *EnableFileCount;
@property (nonatomic, strong) NSNumber *EnableAntiVirus;
@property (nonatomic, strong) NSNumber *EnableFileLocking;
@property (nonatomic, strong) NSNumber *DisableWebAppAccess;
@property (nonatomic, strong) NSNumber *EnableCWC;
@property (nonatomic, strong) NSNumber *EnableIntegrations;
@property (nonatomic, strong) NSArray *IntegrationProviders;
@property (nonatomic, strong) NSNumber *EnableBouncedEmailNotifications;
@property (nonatomic, strong) NSNumber *ShowDownloadLinkInUploadNotification;
@property (nonatomic, strong) NSNumber *AllowDownloadNotificationsWithoutAdmin;
@property (nonatomic, strong) NSNumber *EnableUserInvitations;
@property (nonatomic, strong) NSNumber *EnableClickTrails;
@property (nonatomic, strong) NSNumber *EnableFolderTemplates;
@property (nonatomic, strong) NSNumber *EnableFileDrops;
@property (nonatomic, strong) NSNumber *SpamEmailThreshold;
@property (nonatomic, strong) NSNumber *EnableExternalEmailArchiving;
@property (nonatomic, strong) NSNumber *CreatorCanDelete;
@property (nonatomic, strong) NSNumber *CanStoreItemsInShareFile;
@property (nonatomic, strong) NSNumber *EnableHomeFolders;
@property (nonatomic, strong) NSNumber *EnableCustomBrandingUsesS3;
@property (nonatomic, strong) NSNumber *EnablePromotions;
@property (nonatomic, strong) NSNumber *CanCreateMultiTenantZones;
@property (nonatomic, strong) NSNumber *EnableDLP;
@property (nonatomic, strong) NSNumber *EnableIRM;
@property (nonatomic, strong) NSNumber *EnableOfficeOnlinePreviews;
@property (nonatomic, strong) NSNumber *EnableOfficeOnlineEditing;
@property (nonatomic, strong) NSNumber *RecycleBinDays;
@property (nonatomic, strong) NSNumber *SyncConcurrentTransferThreadsLimit;
@property (nonatomic, strong) NSNumber *HasPHI;
@property (nonatomic, strong) NSNumber *EnableCitrixManagedStorageZones;
@property (nonatomic, strong) NSString *PrimaryStorageBasePath;
@property (nonatomic, strong) NSNumber *EnableSharingConnectorItems;
@property (nonatomic, strong) SFIAccountMessageCode *AccountMessageCode;
@property (nonatomic, strong) NSNumber *EnableSingleIdentity;
@property (nonatomic, strong) NSNumber *EnableDriveMapping;
@property (nonatomic, strong) NSString *NotificationLocale;
@property (nonatomic, strong) NSNumber *RetentionPolicySysAdminOnly;
@property (nonatomic, strong) NSNumber *EnableDocumentApprovalWorkflow;
@property (nonatomic, strong) NSNumber *EnableLocalization;


@end
