//
// SFIAccessControlFailedEntry.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIAccessControlFailedEntry.h"
#import "SFIODataObject.h"

@class SFIAccessControl;
@class SFIODataExceptionMessage;

@implementation SFIAccessControlFailedEntry

@end
