//
// SFIAccountZoneUsage.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIAccountZoneUsage.h"
#import "SFIODataObject.h"

@class SFIZone;

@implementation SFIAccountZoneUsage

@end
