//
// SFIAccessControlDomains.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIAccessControlDomains : SFIODataObject
{
}

/**
   Specifies that the list is interpreted as a list of allowed or disallowed domains
 */
@property (nonatomic, strong) NSString *AccessControlType;
/**
   A list of domain names
 */
@property (nonatomic, strong) NSArray *Domains;


@end
