//
// SFIAccountZoneUsage.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"

@class SFIZone;

@interface SFIAccountZoneUsage : SFIODataObject
{
}

@property (nonatomic, strong) NSNumber *TotalFileSizeBytes;
@property (nonatomic, strong) SFIZone *Zone;
@property (nonatomic, strong) NSNumber *RootFolderCount;
@property (nonatomic, strong) NSNumber *FileCount;


@end
