//
// SFIAsyncOperation.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIAsyncOperation.h"
#import "SFIODataObject.h"

@class SFIAccount;
@class SFIZone;
@class SFIItem;
@class SFIUser;

@implementation SFIAsyncOperation

@end
