//
// SFIAccessControlFailedEntry.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"

@class SFIAccessControl;
@class SFIODataExceptionMessage;

@interface SFIAccessControlFailedEntry : SFIODataObject
{
}

/**
   Entity
 */
@property (nonatomic, strong) SFIAccessControl *AccessControl;
/**
   Failure code
 */
@property (nonatomic, strong) NSString *Code;
/**
   Exception message
 */
@property (nonatomic, strong) SFIODataExceptionMessage *Message;


@end
