//
// SFIAccountMessageCode.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIAccountMessageCode : SFIODataObject
{
}

@property (nonatomic, strong) NSString *AccountType;
@property (nonatomic, strong) NSString *MessageType;
@property (nonatomic, strong) NSDate *CancelDate;


@end
