//
// SFIBillingInfo.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"

@class SFIUser;

@interface SFIBillingInfo : SFIODataObject
{
}

@property (nonatomic, strong) SFIUser *BillingContact;
@property (nonatomic, strong) NSString *Address1;
@property (nonatomic, strong) NSString *Address2;
@property (nonatomic, strong) NSString *City;
@property (nonatomic, strong) NSString *State;
@property (nonatomic, strong) NSString *Country;
@property (nonatomic, strong) NSString *Zip;
@property (nonatomic, strong) NSString *CreditCardFirstName;
@property (nonatomic, strong) NSString *CreditCardLastName;
@property (nonatomic, strong) NSString *CreditCardType;
@property (nonatomic, strong) NSString *CreditCardToken;
@property (nonatomic, strong) NSString *CreditCardExpirationMonth;
@property (nonatomic, strong) NSString *CreditCardExpirationYear;
@property (nonatomic, strong) NSString *CreditCardSecurityCode;


@end
