//
// SFIBillingInfo.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIBillingInfo.h"
#import "SFIODataObject.h"

@class SFIUser;

@implementation SFIBillingInfo

@end
