//
// SFIConnectorGroupZone.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIConnectorGroupZone.h"
#import "SFIODataObject.h"

@class SFIZone;

@implementation SFIConnectorGroupZone

@end
