//
// SFIConnectorGroupAccessControl.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"

@class SFIPrincipal;

@interface SFIConnectorGroupAccessControl : SFIODataObject
{
}

@property (nonatomic, strong) SFIPrincipal *Principal;
@property (nonatomic, strong) NSNumber *CanManage;
@property (nonatomic, strong) NSNumber *CanCreate;


@end
