//
// SFIConnectorGroupAccessControl.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIConnectorGroupAccessControl.h"
#import "SFIODataObject.h"

@class SFIPrincipal;

@implementation SFIConnectorGroupAccessControl

@end
