//
// SFIContact.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIContact.h"
#import "SFIPrincipal.h"
#import "SFIODataObject.h"

@class SFIUser;

@implementation SFIContact

@end
