//
// SFIContact.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIPrincipal.h"
#import "SFIODataObject.h"

@class SFIUser;

@interface SFIContact : SFIPrincipal
{
}

@property (nonatomic, strong) SFIUser *User;
@property (nonatomic, strong) NSString *FirstName;
@property (nonatomic, strong) NSString *LastName;
@property (nonatomic, strong) NSString *Company;
@property (nonatomic, strong) NSString *EmailMedium;
@property (nonatomic, strong) NSString *EmailShort;
@property (nonatomic, strong) NSNumber *IsConfirmed;
@property (nonatomic, strong) NSNumber *Count;


@end
