//
// SFIDeviceWipeReport.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIDeviceWipeReport.h"
#import "SFIODataObject.h"


@implementation SFIDeviceWipeReport

@end
