//
// SFIDevice.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIDevice.h"
#import "SFIODataObject.h"

@class SFIUser;

@implementation SFIDevice

@end
