//
// SFIDeviceLogEntry.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIDeviceLogEntry : SFIODataObject
{
}

/**
   File name
 */
@property (nonatomic, strong) NSString *FileName;
@property (nonatomic, strong) NSString *FileID;
@property (nonatomic, strong) NSNumber *Timestamp;
@property (nonatomic, strong) NSString *AccountID;
@property (nonatomic, strong) NSString *UserID;
@property (nonatomic, strong) NSString *Action;
@property (nonatomic, strong) NSString *AdditionalInfo;


@end
