//
// SFIDeviceUserWipe.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIDeviceUserWipe : SFIODataObject
{
}

/**
   Wipe token
 */
@property (nonatomic, strong) NSString *WipeToken;
/**
   Success
 */
@property (nonatomic, strong) NSString *Success;
/**
   Error message
 */
@property (nonatomic, strong) NSString *ErrorMessage;


@end
