//
// SFIDeviceWipeReport.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIDeviceWipeReport : SFIODataObject
{
}

/**
   Logs
 */
@property (nonatomic, strong) NSArray *Logs;
/**
   Wipe results
 */
@property (nonatomic, strong) NSArray *WipeResults;


@end
