//
// SFIDownloadSpecification.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIDownloadSpecification : SFIODataObject
{
}

@property (nonatomic, strong) NSString *DownloadToken;
@property (nonatomic, strong) NSString *PrepareXmlInfo;
@property (nonatomic, strong) NSURL *DownloadUrl;
@property (nonatomic, strong) NSURL *DownloadPrepStartURL;
@property (nonatomic, strong) NSURL *DownloadPrepStatusURL;


@end
