//
// SFIDiskSpace.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIDiskSpace.h"
#import "SFIODataObject.h"


@implementation SFIDiskSpace

@end
