//
// SFIDeviceUser.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIDeviceUser.h"
#import "SFIODataObject.h"

@class SFIAccount;
@class SFIUser;
@class SFIDevice;

@implementation SFIDeviceUser

@end
