//
//  Autogenerated by a tool.
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface SFIEntityTypeMap : NSObject

+ (NSMutableDictionary *)getModelTypes;

@end
