//
// SFIEnsSubscriptionToken.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIEnsSubscriptionToken : SFIODataObject
{
}

@property (nonatomic, strong) NSString *SubscriptionId;
@property (nonatomic, strong) NSString *EntityId;
@property (nonatomic, strong) NSString *EventTypes;
@property (nonatomic, strong) NSNumber *IncludeProgeny;
@property (nonatomic, strong) NSNumber *LastEventCount;


@end
