//
// SFIEditingPlatformInfo.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIEditingPlatformInfo.h"
#import "SFIODataObject.h"

@class SFIItemProtocolLink;

@implementation SFIEditingPlatformInfo

@end
