//
// SFIESignature.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIESignature.h"
#import "SFIODataObject.h"


@implementation SFIESignature

@end
