//
// SFIEditingPlatformInfo.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"

@class SFIItemProtocolLink;

@interface SFIEditingPlatformInfo : SFIODataObject
{
}

@property (nonatomic, strong) NSString *EditingPlatform;
@property (nonatomic, strong) SFIItemProtocolLink *ItemProtocolLink;


@end
