//
// SFIFileLock.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"

@class SFIPrincipal;

@interface SFIFileLock : SFIODataObject
{
}

@property (nonatomic, strong) NSString *LockId;
@property (nonatomic, strong) NSString *LockType;
@property (nonatomic, strong) SFIPrincipal *Owner;
@property (nonatomic, strong) NSNumber *ExpirationTimeInMinutes;


@end
