//
// SFIFile.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIFile.h"
#import "SFIItem.h"
#import "SFIODataObject.h"

@class SFIItemDlpInfo;
@class SFIItemInfo;
@class SFIUser;
@class SFIFileLock;
@class SFIESignature;

@implementation SFIFile

@end
