//
// SFIFolderTemplate.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"

@class SFIUser;

@interface SFIFolderTemplate : SFIODataObject
{
}

@property (nonatomic, strong) NSString *Name;
@property (nonatomic, strong) NSString *Description;
@property (nonatomic, strong) SFIUser *Creator;
@property (nonatomic, strong) NSArray *Items;


@end
