//
// SFIFileLock.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIFileLock.h"
#import "SFIODataObject.h"

@class SFIPrincipal;

@implementation SFIFileLock

@end
