//
// SFIFavoriteFolder.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIFavoriteFolder.h"
#import "SFIODataObject.h"

@class SFIUser;
@class SFIItem;

@implementation SFIFavoriteFolder

@end
