//
// SFIFolderTemplateItem.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIFolderTemplateItem.h"
#import "SFIODataObject.h"


@implementation SFIFolderTemplateItem

@end
