//
// SFIFolder.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIItem.h"

@class SFIItemInfo;
@class SFIRedirection;
@class SFIFavoriteFolder;

@interface SFIFolder : SFIItem
{
}

/**
   Number of Items defined under this Folder, including sub-folder counts.
 */
@property (nonatomic, strong) NSNumber *FileCount;
/**
   List of Children defined under this folder.
 */
@property (nonatomic, strong) NSArray *Children;
/**
   Defines whether the request to retreive Children is to be navigated to a remote endpoint.
 */
@property (nonatomic, strong) NSNumber *HasRemoteChildren;
/**
   Effective Access Control Permissions for this Folder
 */
@property (nonatomic, strong) SFIItemInfo *Info;
/**
   Redirection endpoint for this Item.
 */
@property (nonatomic, strong) SFIRedirection *Redirection;
/**
   Favorite Folder object associated to this item
 */
@property (nonatomic, strong) SFIFavoriteFolder *FavoriteFolder;
@property (nonatomic, strong) NSString *ZoneService;


@end
