//
// SFIFavoriteFolder.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"

@class SFIUser;
@class SFIItem;

@interface SFIFavoriteFolder : SFIODataObject
{
}

@property (nonatomic, strong) SFIUser *User;
@property (nonatomic, strong) SFIItem *Folder;
@property (nonatomic, strong) NSNumber *SortOrder;
@property (nonatomic, strong) NSString *FolderAlias;
@property (nonatomic, strong) NSString *FolderName;
@property (nonatomic, strong) NSString *Path;
@property (nonatomic, strong) NSNumber *FileSize;
@property (nonatomic, strong) NSDate *CreationDate;
@property (nonatomic, strong) NSString *CreatorFirstName;
@property (nonatomic, strong) NSString *CreatorLastName;


@end
