//
// SFIGroup.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIPrincipal.h"
#import "SFIODataObject.h"

@class SFIUser;
@class SFIAccount;

@interface SFIGroup : SFIPrincipal
{
}

@property (nonatomic, strong) SFIUser *Owner;
@property (nonatomic, strong) SFIAccount *Account;
@property (nonatomic, strong) NSNumber *IsShared;
@property (nonatomic, strong) NSArray *Contacts;


@end
