//
// SFIGroup.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIGroup.h"
#import "SFIPrincipal.h"
#import "SFIODataObject.h"

@class SFIUser;
@class SFIAccount;

@implementation SFIGroup

@end
