//
// SFIGenericConfig.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIGenericConfig.h"
#import "SFIODataObject.h"

@class SFIUser;

@implementation SFIGenericConfig

@end
