//
// SFIItemDlpInfo.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIItemDlpInfo : SFIODataObject
{
}

/**
   File scan status
 */
@property (nonatomic, strong) NSString *Status;


@end
