//
// SFIItemInfo.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"

@class SFIAccessControl;

@interface SFIItemInfo : SFIODataObject
{
}

@property (nonatomic, strong) SFIAccessControl *CurrentAccessControl;
@property (nonatomic, strong) NSNumber *HasVroot;
@property (nonatomic, strong) NSNumber *IsSystemRoot;
@property (nonatomic, strong) NSNumber *IsAccountRoot;
@property (nonatomic, strong) NSNumber *IsVRoot;
@property (nonatomic, strong) NSNumber *IsMyFolders;
@property (nonatomic, strong) NSNumber *IsAHomeFolder;
@property (nonatomic, strong) NSNumber *IsMyHomeFolder;
@property (nonatomic, strong) NSNumber *IsAStartFolder;
@property (nonatomic, strong) NSNumber *IsSharedFolder;
@property (nonatomic, strong) NSNumber *IsPassthrough;
@property (nonatomic, strong) NSNumber *IsVersioned;
@property (nonatomic, strong) NSNumber *CanAddFolder;
@property (nonatomic, strong) NSNumber *CanAddNode;
@property (nonatomic, strong) NSNumber *CanView;
@property (nonatomic, strong) NSNumber *CanDownload;
@property (nonatomic, strong) NSNumber *CanWatermarkDownload;
@property (nonatomic, strong) NSNumber *CanDocViewerPrint;
@property (nonatomic, strong) NSNumber *CanUpload;
@property (nonatomic, strong) NSNumber *CanSend;
@property (nonatomic, strong) NSNumber *CanDeleteCurrentItem;
@property (nonatomic, strong) NSNumber *CanDeleteChildItems;
@property (nonatomic, strong) NSNumber *CanManagePermissions;
@property (nonatomic, strong) NSNumber *CanEditFolderOpts;
@property (nonatomic, strong) NSNumber *CanEditRetentionPolicy;
@property (nonatomic, strong) NSString *FolderPayID;
@property (nonatomic, strong) NSNumber *ShowFolderPayBuyButton;
@property (nonatomic, strong) NSString *TreeMode;
@property (nonatomic, strong) NSString *Versioning;
@property (nonatomic, strong) NSNumber *TreeModeOperationAllowed;
@property (nonatomic, strong) NSString *TreeModeSourceId;
@property (nonatomic, strong) NSString *ForcedSortField;
@property (nonatomic, strong) NSString *ForcedSortOrder;
@property (nonatomic, strong) NSNumber *MaxVersions;
@property (nonatomic, strong) NSString *DocumentViewerPrinting;
@property (nonatomic, strong) NSString *WatermarkedDownloads;
@property (nonatomic, strong) NSArray *OptionPropagation;
@property (nonatomic, strong) NSString *ViewOnlyWatermarkText;
@property (nonatomic, strong) NSString *SortField;
@property (nonatomic, strong) NSString *SortDirection;


@end
