//
// SFIInboxMetadata.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIInboxMetadata : SFIODataObject
{
}

@property (nonatomic, strong) NSNumber *UnreadSendUnarchived;
@property (nonatomic, strong) NSNumber *UnreadRequestUnarchived;


@end
