//
// SFIIrmPrimaryAccessRightParams.m
// sfapiv3
// 
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIIrmPrimaryAccessRightParams.h"
#import "SFIODataObject.h"


@implementation SFIIrmPrimaryAccessRightParams

@end
