//
// SFIInboxMetadata.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIInboxMetadata.h"
#import "SFIODataObject.h"


@implementation SFIInboxMetadata

@end
