//
// SFIItemProtocolLink.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"

@class SFIRedirection;

@interface SFIItemProtocolLink : SFIODataObject
{
}

@property (nonatomic, strong) NSString *Link;
@property (nonatomic, strong) SFIRedirection *Redirection;


@end
