//
// SFIItemProtocolLink.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIItemProtocolLink.h"
#import "SFIODataObject.h"

@class SFIRedirection;

@implementation SFIItemProtocolLink

@end
