//
// SFILink.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIItem.h"
#import "SFIODataObject.h"


@interface SFILink : SFIItem
{
}

/**
   Universal Reference Identifier for this Link object
 */
@property (nonatomic, strong) NSURL *Uri;


@end
