//
// SFIMarketAnalytics.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIMarketAnalytics : SFIODataObject
{
}

@property (nonatomic, strong) NSNumber *ConversionIndex;
@property (nonatomic, strong) NSNumber *ConversionIndex2;
@property (nonatomic, strong) NSNumber *LtvIndex;
@property (nonatomic, strong) NSNumber *PlanValue;


@end
