//
// SFIMarketAnalytics.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIMarketAnalytics.h"
#import "SFIODataObject.h"


@implementation SFIMarketAnalytics

@end
