//
// SFInboxMetadata.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFInboxMetadata : SFODataObject
{
}

@property (nonatomic, strong) NSNumber *UnreadSendUnarchived;
@property (nonatomic, strong) NSNumber *UnreadRequestUnarchived;


@end
