//
// SFINote.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIItem.h"
#import "SFIODataObject.h"


@interface SFINote : SFIItem
{
}



@end
