//
// SFINote.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFINote.h"
#import "SFIItem.h"
#import "SFIODataObject.h"


@implementation SFINote

@end
