//
// SFINotifyUsersParams.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFINotifyUsersParams : SFIODataObject
{
}

@property (nonatomic, strong) NSArray *UserIds;
@property (nonatomic, strong) NSString *CustomMessage;


@end
