//
// SFINotification.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFINotification : SFIODataObject
{
}

@property (nonatomic, strong) NSString *NotificationType;
@property (nonatomic, strong) NSString *EventID;
@property (nonatomic, strong) NSString *SenderID;
@property (nonatomic, strong) NSString *RecipientID;
@property (nonatomic, strong) NSString *FromName;
@property (nonatomic, strong) NSString *FromEmail;
@property (nonatomic, strong) NSString *ReplyTo;
@property (nonatomic, strong) NSString *To;
@property (nonatomic, strong) NSString *CC;
@property (nonatomic, strong) NSString *BCC;
@property (nonatomic, strong) NSString *Subject;
@property (nonatomic, strong) NSString *Message;
@property (nonatomic, strong) NSString *PlainTextMessage;
@property (nonatomic, strong) NSDate *DateSent;
@property (nonatomic, strong) NSString *Status;
@property (nonatomic, strong) NSNumber *IsImportant;
@property (nonatomic, strong) NSNumber *ReadReceipt;
@property (nonatomic, strong) NSArray *AttachmentPaths;
@property (nonatomic, strong) NSNumber *ForceEmailFromShareFile;
@property (nonatomic, strong) NSArray *MergeNames;
@property (nonatomic, strong) NSArray *MergeValues;
@property (nonatomic, strong) NSNumber *RecordSend;
@property (nonatomic, strong) NSNumber *IsModelBased;


@end
