//
// SFINotification.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFINotification.h"
#import "SFIODataObject.h"


@implementation SFINotification

@end
