//
// SFIndustry.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFIndustry : SFODataObject
{
}

@property (nonatomic, strong) NSString *Name;


@end
