//
// SFIOutlookInformation.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"

@class SFIOutlookInformationOptionString;
@class SFIOutlookInformationOptionBool;
@class SFIOutlookInformationOptionInt;

@interface SFIOutlookInformation : SFIODataObject
{
}

@property (nonatomic, strong) SFIOutlookInformationOptionString *DownloadInfoLevel;
@property (nonatomic, strong) SFIOutlookInformationOptionString *UploadInfoLevel;
@property (nonatomic, strong) SFIOutlookInformationOptionBool *NotifyOnDownload;
@property (nonatomic, strong) SFIOutlookInformationOptionBool *NotifyOnUpload;
@property (nonatomic, strong) SFIOutlookInformationOptionInt *MaxDownloads;
@property (nonatomic, strong) SFIOutlookInformationOptionString *LinkExpiration;
@property (nonatomic, strong) SFIOutlookInformationOptionString *RequestText;
@property (nonatomic, strong) SFIOutlookInformationOptionString *SendText;
@property (nonatomic, strong) SFIOutlookInformationOptionString *BannerHTML;
@property (nonatomic, strong) SFIOutlookInformationOptionBool *UseBanner;
@property (nonatomic, strong) SFIOutlookInformationOptionBool *AutoConvert;
@property (nonatomic, strong) SFIOutlookInformationOptionInt *ConvertAbove;
@property (nonatomic, strong) SFIOutlookInformationOptionBool *AttachPaperclip;
@property (nonatomic, strong) SFIOutlookInformationOptionString *EncryptedEmailRecipientVerification;
@property (nonatomic, strong) SFIOutlookInformationOptionString *EncryptedEmailExpiration;
@property (nonatomic, strong) SFIOutlookInformationOptionBool *EncryptedEmailNotifyOnRead;


@end
