//
// SFIODataFeed.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIODataFeed : SFIODataObject
{
}

@property (nonatomic, strong) NSNumber *count;
@property (nonatomic, strong) NSArray *value;
@property (nonatomic, strong) NSString *nextLink;


@end
