//
// SFIOutlookInformationOptionString.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIOutlookInformationOptionString : SFIODataObject
{
}

@property (nonatomic, strong) NSNumber *Locked;
@property (nonatomic, strong) NSString *Value;


@end
