//
// SFIOutlookInformationOptionBool.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIOutlookInformationOptionBool.h"
#import "SFIODataObject.h"


@implementation SFIOutlookInformationOptionBool

@end
