//
// SFIOutlookInformation.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIOutlookInformation.h"
#import "SFIODataObject.h"

@class SFIOutlookInformationOptionString;
@class SFIOutlookInformationOptionBool;
@class SFIOutlookInformationOptionInt;

@implementation SFIOutlookInformation

@end
