//
// SFIPrincipal.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIPrincipal.h"
#import "SFIODataObject.h"


@implementation SFIPrincipal

@end
