//
// SFIPreviewPlatformInfo.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"

@class SFIItemProtocolLink;

@interface SFIPreviewPlatformInfo : SFIODataObject
{
}

/**
   Indicates the Preview platform
 */
@property (nonatomic, strong) NSString *PreviewPlatform;
/**
   Indicates the ItemProtocolLink for this Preview platform
 */
@property (nonatomic, strong) SFIItemProtocolLink *ItemProtocolLink;


@end
