//
// SFIPreviewPlatformInfo.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIPreviewPlatformInfo.h"
#import "SFIODataObject.h"

@class SFIItemProtocolLink;

@implementation SFIPreviewPlatformInfo

@end
