//
// SFIPlanFeatures.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIPlanFeatures : SFIODataObject
{
}

@property (nonatomic, strong) NSString *PlanType;
@property (nonatomic, strong) NSNumber *API;
@property (nonatomic, strong) NSNumber *Outlook;
@property (nonatomic, strong) NSNumber *DriveMapping;
@property (nonatomic, strong) NSNumber *CLI;
@property (nonatomic, strong) NSNumber *FTP;
@property (nonatomic, strong) NSNumber *FTPS;
@property (nonatomic, strong) NSNumber *Sync;
@property (nonatomic, strong) NSNumber *AntiVirus;
@property (nonatomic, strong) NSNumber *RequireLoginOnDownload;
@property (nonatomic, strong) NSNumber *MaxFileMB;
@property (nonatomic, strong) NSNumber *PlanStorMB;
@property (nonatomic, strong) NSNumber *PlanBandMB;
@property (nonatomic, strong) NSString *SystemName;
@property (nonatomic, strong) NSString *SystemType;
@property (nonatomic, strong) NSNumber *HasOutlookOptions;
@property (nonatomic, strong) NSNumber *SimpleMAPI;
@property (nonatomic, strong) NSNumber *ForceAttachLink;
@property (nonatomic, strong) NSString *UsedStorMB;
@property (nonatomic, strong) NSString *UsedStorUtcTicks;
@property (nonatomic, strong) NSString *UsedStorBytes;
@property (nonatomic, strong) NSNumber *IsEmployee;
@property (nonatomic, strong) NSNumber *IsAdministrator;
@property (nonatomic, strong) NSNumber *CanCreateRootFolders;
@property (nonatomic, strong) NSNumber *CanUseFileBox;
@property (nonatomic, strong) NSNumber *IsConfirmed;
@property (nonatomic, strong) NSNumber *CanResetPassword;
@property (nonatomic, strong) NSString *PasswordRegEx;
@property (nonatomic, strong) NSNumber *CanManageMySettings;
@property (nonatomic, strong) NSString *HomeFolder;
@property (nonatomic, strong) NSNumber *EnableAutoUpdate;
@property (nonatomic, strong) NSNumber *EnableTopLevelView;


@end
