//
// SFIQuerySorting.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIQuerySorting : SFIODataObject
{
}

/**
   What property to sort the search results by. Set to "" to not sort them
 */
@property (nonatomic, strong) NSString *SortBy;
/**
   Whether the sort order should be ascending or not
 */
@property (nonatomic, strong) NSNumber *Ascending;


@end
