//
// SFIQueryPaging.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIQueryPaging : SFIODataObject
{
}

/**
   Deprecated, use the Skip property to skip some number of results
 */
@property (nonatomic, strong) NSNumber *PageNumber;
/**
   Deprecated, use the Count property
 */
@property (nonatomic, strong) NSNumber *PageSize;
/**
   The number of search results to get
 */
@property (nonatomic, strong) NSNumber *Count;
/**
   How many results to skip before returning "Count" number results.
 */
@property (nonatomic, strong) NSNumber *Skip;


@end
