//
// SFIRequireWebPopResult.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIRequireWebPopResult : SFIODataObject
{
}

@property (nonatomic, strong) NSNumber *RequireWebPop;


@end
