//
// SFIrmPrimaryAccessRightParams.h
// 
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFIrmPrimaryAccessRightParams : SFODataObject
{

}

/**
Allows user to view the documents
*/
@property (nonatomic, strong) NSNumber *View;
/**
Allows user to use LightViewer client to view the documents
*/
@property (nonatomic, strong) NSNumber *LightViewer;
/**
Allows user to print the documents
*/
@property (nonatomic, strong) NSNumber *Print;
/**
Allows user to edit the documents
*/
@property (nonatomic, strong) NSNumber *Edit;
/**
Allows user to have full control over the document.
*/
@property (nonatomic, strong) NSNumber *FullControl;
/**
Allows user to copy the content into clipboard from the document.
*/
@property (nonatomic, strong) NSNumber *CopyData;
/**
Allows user to use native screen capture tools.
*/
@property (nonatomic, strong) NSNumber *ScreenCapture;
/**
Allows user to run macros. User cannot even view a macro file if this access right is set to false.
*/
@property (nonatomic, strong) NSNumber *Macro;
/**
Allows user to access the documents offline
*/
@property (nonatomic, strong) NSNumber *OfflineAccess;


@end