//
// SFIrmClassification.h
// 
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"

@class SFIrmPrimaryAccessRightParams;

@interface SFIrmClassification : SFODataObject
{

}

/**
Name of the Irm Classification
*/
@property (nonatomic, strong) NSString *Name;
/**
Description of the Irm Classification if any
*/
@property (nonatomic, strong) NSString *Description;
/**
AccessRight permissions on an IRM Classification
*/
@property (nonatomic, strong) SFIrmPrimaryAccessRightParams *PrimaryAccessRightParams;
/**
Use this flag to enable/ disable the Irm Classification.
If disabled, this Irm Classification won't show up in the List of active IrmClassifications on an account.
*/
@property (nonatomic, strong) NSNumber *IsEnabled;
/**
Defines the numner of days after which the user won't be access the documents protected with this classification.
*/
@property (nonatomic, strong) NSNumber *NumberOfProtectionDays;


@end