//
// SFIReport.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIReport.h"
#import "SFIODataObject.h"

@class SFIItem;
@class SFIUser;

@implementation SFIReport

@end
