//
// SFIRemoteUpload.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIRemoteUpload.h"
#import "SFIODataObject.h"


@implementation SFIRemoteUpload

@end
