//
// SFIRemoteUploadRequestParams.h
// 
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIUploadRequestParams.h"
#import "SFIODataObject.h"

@class SFIContact;

@interface SFIRemoteUploadRequestParams : SFIUploadRequestParams
{

}

@property (nonatomic, strong) SFIContact *Creator;


@end
