//
// SFIrmPrimaryAccessRightParams.m
// sfapiv3
// 
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIrmPrimaryAccessRightParams.h"
#import "SFODataObject.h"


@implementation SFIrmPrimaryAccessRightParams

@end