//
// SFIrmClassification.m
// sfapiv3
// 
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIrmClassification.h"
#import "SFODataObject.h"

@class SFIrmPrimaryAccessRightParams;

@implementation SFIrmClassification

@end