//
// SFIRemoteUploadRequestParams.m
// sfapiv3
// 
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIRemoteUploadRequestParams.h"
#import "SFIUploadRequestParams.h"
#import "SFIODataObject.h"

@class SFIContact;

@implementation SFIRemoteUploadRequestParams

@end
