//
// SFISession.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFISession.h"
#import "SFIODataObject.h"

@class SFIPrincipal;
@class SFIDeviceUser;

@implementation SFISession

@end
