//
// SFISearchQuery.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"

@class SFIQuery;
@class SFIQueryPaging;
@class SFIQuerySorting;

@interface SFISearchQuery : SFIODataObject
{
}

/**
   Information about the query to run
 */
@property (nonatomic, strong) SFIQuery *Query;
/**
   Paging info about the search results
 */
@property (nonatomic, strong) SFIQueryPaging *Paging;
/**
   How the search results should be sorted
 */
@property (nonatomic, strong) SFIQuerySorting *Sort;
/**
   Timeout for the search request in seconds
 */
@property (nonatomic, strong) NSNumber *TimeoutInSeconds;


@end
