//
// SFIShareSendParams.h
// 
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"

@class SFIShareAccessRight;

@interface SFIShareSendParams : SFIODataObject
{

}

/**
List of Item Ids to be sent
*/
@property (nonatomic, strong) NSArray *Items;
/**
List of emails to whom this Share should be sent
*/
@property (nonatomic, strong) NSArray *Emails;
/**
The subject of the Share email
*/
@property (nonatomic, strong) NSString *Subject;
/**
A message to be included in the Share email body
*/
@property (nonatomic, strong) NSString *Body;
/**
If true, the Share sender will be cc'd in the Share email
*/
@property (nonatomic, strong) NSNumber *CcSender;
/**
If true, recipients will need to login to access the Share
*/
@property (nonatomic, strong) NSNumber *RequireLogin;
/**
If true, anyone with the link can access the Share. Cannot be true if RequireLogin is true
*/
@property (nonatomic, strong) NSNumber *SendAnon;
/**
If true, a recipient will need to provide their full name and email to access the Share. Cannot be true if RequireLogin is true
*/
@property (nonatomic, strong) NSNumber *RequireUserInfo;
/**
Number of days until access to this Share expires
*/
@property (nonatomic, strong) NSNumber *ExpirationDays;
/**
If true, the sender will receive an email notification when the Share items are downloaded
*/
@property (nonatomic, strong) NSNumber *NotifyOnDownload;
/**
If true, the Share items can only be viewed but not downloaded. Requires account preference EnableViewOnly to work
*/
@property (nonatomic, strong) NSNumber *IsViewOnly;
/**
Maximum number of times each recipient can download the Share items
*/
@property (nonatomic, strong) NSNumber *MaxDownloads;
/**
When enabled the items are identified by stream IDs instead of item IDs.
Applies to Send Shares only. (FINRA enabled accounts cannot use this)
*/
@property (nonatomic, strong) NSNumber *UsesStreamIDs;
/**
Used to define the share type and share action types
*/
@property (nonatomic, strong) SFIShareAccessRight *ShareAccessRight;


@end
