//
// SFISSOAccountProvider.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFISSOAccountProvider.h"
#import "SFIODataObject.h"

@class SFIAccount;

@implementation SFISSOAccountProvider

@end
