//
// SFIStorageCenter.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIStorageCenter.h"
#import "SFIODataObject.h"

@class SFIZone;

@implementation SFIStorageCenter

@end
