//
// SFISSOInfoEntry.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFISSOInfoEntry : SFIODataObject
{
}

@property (nonatomic, strong) NSString *Key;
@property (nonatomic, strong) NSString *Value;


@end
