//
// SFIShareAlias.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIShareAlias.h"
#import "SFIODataObject.h"

@class SFIUser;
@class SFIShare;

@implementation SFIShareAlias

@end
