//
// SFISession.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"

@class SFIPrincipal;
@class SFIDeviceUser;

@interface SFISession : SFIODataObject
{
}

@property (nonatomic, strong) SFIPrincipal *Principal;
@property (nonatomic, strong) NSString *AuthenticationType;
@property (nonatomic, strong) NSString *OAuth2ClientName;
@property (nonatomic, strong) NSString *Tool;
@property (nonatomic, strong) NSString *Version;
@property (nonatomic, strong) NSString *ClientIPAddress;
@property (nonatomic, strong) NSNumber *IsAuthenticated;
@property (nonatomic, strong) NSString *Name;
@property (nonatomic, strong) SFIDeviceUser *DeviceUser;


@end
