//
// SFISearchResults.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFISearchResults : SFIODataObject
{
}

/**
   Are these only partial results?
 */
@property (nonatomic, strong) NSNumber *PartialResults;
/**
   Collection of search result hits
 */
@property (nonatomic, strong) NSArray *Results;
/**
   Did the search query timeout?
 */
@property (nonatomic, strong) NSNumber *TimedOut;


@end
