//
// SFIShareItemHistory.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIShareItemHistory : SFIODataObject
{
}

@property (nonatomic, strong) NSString *Title;
@property (nonatomic, strong) NSString *Recipient;
@property (nonatomic, strong) NSString *ActivityType;
@property (nonatomic, strong) NSDate *DownloadDate;


@end
