//
// SFIShareAccessRight.h
// 
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIShareAccessRight : SFIODataObject
{

}

/**
Localized text for downstream clients to use for displaying options
*/
@property (nonatomic, strong) NSString *DisplayText;
/**
Share Access Right Type
*/
@property (nonatomic, strong) NSString *AccessRightType;


@end
