//
// SFISearchResults.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFISearchResults.h"
#import "SFIODataObject.h"


@implementation SFISearchResults

@end
