//
// SFISearchResult.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFISearchResult : SFIODataObject
{
}

@property (nonatomic, strong) NSNumber *Rank;
@property (nonatomic, strong) NSNumber *Score;
@property (nonatomic, strong) NSString *ItemID;
@property (nonatomic, strong) NSString *ParentID;
@property (nonatomic, strong) NSString *ParentName;
@property (nonatomic, strong) NSString *ItemType;
@property (nonatomic, strong) NSString *FileName;
@property (nonatomic, strong) NSString *DisplayName;
@property (nonatomic, strong) NSNumber *Size;
@property (nonatomic, strong) NSString *CreatorID;
@property (nonatomic, strong) NSString *CreatorName;
@property (nonatomic, strong) NSString *CreatorFirstName;
@property (nonatomic, strong) NSString *CreatorLastName;
@property (nonatomic, strong) NSString *CreationDate;
@property (nonatomic, strong) NSString *Details;
@property (nonatomic, strong) NSString *MD5;
@property (nonatomic, strong) NSNumber *PreviewStatus;
@property (nonatomic, strong) NSNumber *VirusStatus;
@property (nonatomic, strong) NSString *Url;
@property (nonatomic, strong) NSNumber *CanDownload;
@property (nonatomic, strong) NSNumber *CanView;
@property (nonatomic, strong) NSNumber *CanDelete;
@property (nonatomic, strong) NSString *ParentSemanticPath;
@property (nonatomic, strong) NSString *Path;
@property (nonatomic, strong) NSString *StreamID;
@property (nonatomic, strong) NSString *AccountID;


@end
