//
// SFIShareAlias.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"

@class SFIUser;
@class SFIShare;

@interface SFIShareAlias : SFIODataObject
{
}

@property (nonatomic, strong) SFIUser *User;
@property (nonatomic, strong) SFIShare *Share;
@property (nonatomic, strong) NSString *Email;
@property (nonatomic, strong) NSNumber *Downloads;
@property (nonatomic, strong) NSNumber *IsConsumed;
@property (nonatomic, strong) NSNumber *IsArchived;
@property (nonatomic, strong) NSNumber *IsRead;
/**
   Uri to access the share through the Web portal
 */
@property (nonatomic, strong) NSURL *Uri;


@end
