//
// SFIShareSettings.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIShareSettings : SFIODataObject
{
}

@property (nonatomic, strong) NSNumber *NotifyOnUse;


@end
