//
// SFIShareResendParams.h
// 
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIShareResendParams : SFIODataObject
{

}

/**
The ID of the existing share
*/
@property (nonatomic, strong) NSString *ShareId;
/**
These can be email addresses or group IDs
*/
@property (nonatomic, strong) NSArray *Recipients;
@property (nonatomic, strong) NSString *Subject;
/**
Message included in the share notification
*/
@property (nonatomic, strong) NSString *Body;
/**
Send a copy of the notification to the cender
*/
@property (nonatomic, strong) NSNumber *CcSender;
@property (nonatomic, strong) NSNumber *NotifyOnUse;


@end
