//
// SFISearchQuery.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFISearchQuery.h"
#import "SFIODataObject.h"

@class SFIQuery;
@class SFIQueryPaging;
@class SFIQuerySorting;

@implementation SFISearchQuery

@end
