//
// SFIService.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIService : SFIODataObject
{
}

@property (nonatomic, strong) NSString *AddOnCode;
@property (nonatomic, strong) NSNumber *Licenses;


@end
