//
// SFISymbolicLink.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIFolder.h"
#import "SFIODataObject.h"

@class SFIConnectorGroup;

@interface SFISymbolicLink : SFIFolder
{
}

@property (nonatomic, strong) NSURL *Link;
@property (nonatomic, strong) SFIConnectorGroup *ConnectorGroup;


@end
