//
// SFIShareSendParams.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIShareSendParams.h"
#import "SFIODataObject.h"

@class SFIShareAccessRight;

@implementation SFIShareSendParams

@end
