//
// SFISymbolicLink.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFISymbolicLink.h"
#import "SFIFolder.h"
#import "SFIODataObject.h"

@class SFIConnectorGroup;

@implementation SFISymbolicLink

@end
