//
// SFIShare.m
// sfapiv3
// 
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIShare.h"
#import "SFIODataObject.h"

@class SFIItem;
@class SFIUser;
@class SFIZone;
@class SFIRedirection;
@class SFIShareSettings;
@class SFIShareAccessRight;

@implementation SFIShare

@end
