//
// SFISimpleSearchQuery.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFISimpleSearchQuery.h"
#import "SFIODataObject.h"

@class SFISimpleQuery;
@class SFIQueryPaging;
@class SFIQuerySorting;

@implementation SFISimpleSearchQuery

@end
