//
// SFItemDlpInfo.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFItemDlpInfo.h"
#import "SFODataObject.h"


@implementation SFItemDlpInfo

@end
