//
// SFITenantZoneUsageReport.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFITenantZoneUsageReport.h"
#import "SFIODataObject.h"


@implementation SFITenantZoneUsageReport

@end
