//
// SFItemProtocolLink.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFItemProtocolLink.h"
#import "SFODataObject.h"

@class SFRedirection;

@implementation SFItemProtocolLink

@end
