//
// SFItemProtocolLink.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"

@class SFRedirection;

@interface SFItemProtocolLink : SFODataObject
{
}

@property (nonatomic, strong) NSString *Link;
@property (nonatomic, strong) SFRedirection *Redirection;


@end
