//
// SFITenantZoneUsageReport.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFITenantZoneUsageReport : SFIODataObject
{
}

@property (nonatomic, strong) NSDictionary *TenantsToZones;


@end
