//
// SFItemDlpInfo.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFItemDlpInfo : SFODataObject
{
}

/**
   File scan status
 */
@property (nonatomic, strong) NSString *Status;


@end
