//
// SFItemInfo.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFItemInfo.h"
#import "SFODataObject.h"

@class SFAccessControl;

@implementation SFItemInfo

@end
