//
// SFItem.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "SFODataObject.h"

@class SFUser;
@class SFZone;
@class SFAccount;

@interface SFItem : SFODataObject
{
}

@property (nonatomic, strong) NSString *Name;
@property (nonatomic, strong) NSString *FileName;
@property (nonatomic, strong) SFUser *Creator;
@property (nonatomic, strong) SFItem *Parent;
@property (nonatomic, strong) NSArray *AccessControls;
@property (nonatomic, strong) SFZone *Zone;
@property (nonatomic, strong) NSDate *CreationDate;
@property (nonatomic, strong) NSDate *ProgenyEditDate;
@property (nonatomic, strong) NSDate *ClientCreatedDate;
@property (nonatomic, strong) NSDate *ClientModifiedDate;
@property (nonatomic, strong) NSDate *ExpirationDate;
@property (nonatomic, strong) NSString *Description;
@property (nonatomic, strong) NSNumber *DiskSpaceLimit;
@property (nonatomic, strong) NSNumber *IsHidden;
@property (nonatomic, strong) NSNumber *BandwidthLimitInMB;
@property (nonatomic, strong) SFUser *Owner;
@property (nonatomic, strong) SFAccount *Account;
@property (nonatomic, strong) NSNumber *FileSizeInKB;
@property (nonatomic, strong) NSString *Path;
@property (nonatomic, strong) NSString *CreatorFirstName;
@property (nonatomic, strong) NSString *CreatorLastName;
@property (nonatomic, strong) NSNumber *ExpirationDays;
@property (nonatomic, strong) NSNumber *FileSizeBytes;
@property (nonatomic, strong) NSString *PreviewStatus;
@property (nonatomic, strong) NSArray *PreviewPlatformsSupported;
@property (nonatomic, strong) NSArray *EditingPlatformsSupported;
@property (nonatomic, strong) NSNumber *MaxPreviewSize;
@property (nonatomic, strong) NSNumber *HasPendingDeletion;
@property (nonatomic, strong) NSString *AssociatedFolderTemplateID;
@property (nonatomic, strong) NSNumber *IsTemplateOwned;
@property (nonatomic, strong) NSNumber *HasPermissionInfo;
@property (nonatomic, strong) NSNumber *State;
@property (nonatomic, strong) NSString *StreamID;
@property (nonatomic, strong) NSString *CreatorNameShort;
@property (nonatomic, strong) NSNumber *HasMultipleVersions;
@property (nonatomic, strong) NSNumber *HasPendingAsyncOp;


@end
