//
// SFIToolInformation.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIToolInformation : SFIODataObject
{
}

@property (nonatomic, strong) NSString *ToolName;
@property (nonatomic, strong) NSString *Version;


@end
