//
// SFItem.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFItem.h"
#import "SFODataObject.h"

@class SFUser;
@class SFZone;
@class SFAccount;

@implementation SFItem

@end
