//
// SFIUserInfo.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"

@class SFIPlanFeatures;

@interface SFIUserInfo : SFIODataObject
{
}

@property (nonatomic, strong) NSString *CompanyName;
@property (nonatomic, strong) NSString *PlanName;
@property (nonatomic, strong) SFIPlanFeatures *PlanFeatures;
@property (nonatomic, strong) NSString *ApplicationUrl;
@property (nonatomic, strong) NSString *StorageCenterUrl;


@end
