//
// SFIUserConfirmationSettings.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIUserConfirmationSettings : SFIODataObject
{
}

@property (nonatomic, strong) NSString *FirstName;
@property (nonatomic, strong) NSString *LastName;
@property (nonatomic, strong) NSString *Company;
@property (nonatomic, strong) NSString *Password;
@property (nonatomic, strong) NSString *SecurityQuestion;
@property (nonatomic, strong) NSString *SecurityQuestionAnswer;
@property (nonatomic, strong) NSString *DayLightName;
@property (nonatomic, strong) NSString *UTCOffset;
@property (nonatomic, strong) NSString *DateFormat;
@property (nonatomic, strong) NSString *TimeFormat;
@property (nonatomic, strong) NSNumber *EmailInterval;


@end
