//
// SFIUserInfo.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIUserInfo.h"
#import "SFIODataObject.h"

@class SFIPlanFeatures;

@implementation SFIUserInfo

@end
