//
// SFIUploadRequestParams.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIUploadRequestParams : SFIODataObject
{
}

@property (nonatomic, strong) NSString *Method;
@property (nonatomic, strong) NSNumber *Raw;
@property (nonatomic, strong) NSString *FileName;
@property (nonatomic, strong) NSNumber *FileSize;
@property (nonatomic, strong) NSString *BatchId;
@property (nonatomic, strong) NSNumber *BatchLast;
@property (nonatomic, strong) NSNumber *CanResume;
@property (nonatomic, strong) NSNumber *StartOver;
@property (nonatomic, strong) NSNumber *Unzip;
@property (nonatomic, strong) NSNumber *Overwrite;
@property (nonatomic, strong) NSString *Opid;
@property (nonatomic, strong) NSString *Title;
@property (nonatomic, strong) NSString *Tool;
@property (nonatomic, strong) NSString *Details;
@property (nonatomic, strong) NSNumber *IsSend;
@property (nonatomic, strong) NSString *SendGuid;
@property (nonatomic, strong) NSNumber *Notify;
@property (nonatomic, strong) NSNumber *ThreadCount;
@property (nonatomic, strong) NSDate *ClientCreatedDate;
@property (nonatomic, strong) NSDate *ClientModifiedDate;


@end
