//
// SFIUserConfirmRequirement.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"

@class SFIUser;

@interface SFIUserConfirmRequirement : SFIODataObject
{
}

@property (nonatomic, strong) NSString *AuthenticationId;
@property (nonatomic, strong) NSNumber *IsProbableSAMLOnlyUser;
@property (nonatomic, strong) NSNumber *IsADLinked;
@property (nonatomic, strong) NSString *ADUserName;
@property (nonatomic, strong) NSString *TempPassword;
@property (nonatomic, strong) SFIUser *User;


@end
