//
// SFIUserUsage.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIUserUsage : SFIODataObject
{
}

@property (nonatomic, strong) NSNumber *EmployeeMax;
@property (nonatomic, strong) NSNumber *EmployeeCount;
@property (nonatomic, strong) NSNumber *ClientCount;


@end
