//
// SFIUser.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIUser.h"
#import "SFIPrincipal.h"
#import "SFIODataObject.h"

@class SFIAccount;
@class SFIZone;
@class SFIUserPreferences;
@class SFIUserSecurity;
@class SFIFolder;
@class SFIUserInfo;

@implementation SFIUser

@end
