//
// SFIUser.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIPrincipal.h"
#import "SFIODataObject.h"

@class SFIAccount;
@class SFIZone;
@class SFIUserPreferences;
@class SFIUserSecurity;
@class SFIFolder;
@class SFIUserInfo;

@interface SFIUser : SFIPrincipal
{
}

@property (nonatomic, strong) SFIAccount *Account;
@property (nonatomic, strong) NSString *Company;
@property (nonatomic, strong) NSNumber *TotalSharedFiles;
@property (nonatomic, strong) NSNumber *Contacted;
@property (nonatomic, strong) NSString *FullName;
@property (nonatomic, strong) NSString *ReferredBy;
@property (nonatomic, strong) NSArray *Notifications;
@property (nonatomic, strong) SFIZone *DefaultZone;
@property (nonatomic, strong) NSString *FirstName;
@property (nonatomic, strong) NSString *LastName;
@property (nonatomic, strong) NSDate *DateCreated;
@property (nonatomic, strong) NSString *FullNameShort;
@property (nonatomic, strong) NSArray *Emails;
@property (nonatomic, strong) NSNumber *IsConfirmed;
@property (nonatomic, strong) NSString *Password;
@property (nonatomic, strong) SFIUserPreferences *Preferences;
@property (nonatomic, strong) SFIUserSecurity *Security;
@property (nonatomic, strong) NSArray *FavoriteFolders;
@property (nonatomic, strong) SFIFolder *HomeFolder;
@property (nonatomic, strong) NSArray *Devices;
@property (nonatomic, strong) NSArray *Integrations;
@property (nonatomic, strong) SFIFolder *VirtualRoot;
@property (nonatomic, strong) NSArray *Roles;
@property (nonatomic, strong) SFIUserInfo *Info;
@property (nonatomic, strong) NSString *AffiliatedPartnerUserId;


@end
