//
// SFIZone.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIPrincipal.h"
#import "SFIODataObject.h"

@class SFIAccount;

@interface SFIZone : SFIPrincipal
{
}

@property (nonatomic, strong) NSString *Secret;
@property (nonatomic, strong) NSString *ZoneType;
@property (nonatomic, strong) SFIAccount *Account;
@property (nonatomic, strong) NSNumber *HeartBeatTolerance;
@property (nonatomic, strong) NSNumber *PingBackInterval;
@property (nonatomic, strong) NSString *Version;
@property (nonatomic, strong) NSString *ZoneServices;
@property (nonatomic, strong) NSNumber *IsHIPAAZone;
@property (nonatomic, strong) NSNumber *IsMultiTenant;
@property (nonatomic, strong) NSArray *StorageCenters;


@end
