//
// SFIZone.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIZone.h"
#import "SFIPrincipal.h"
#import "SFIODataObject.h"

@class SFIAccount;

@implementation SFIZone

@end
