//
// SFIZoneUsageBreakdown.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataObject.h"


@interface SFIZoneUsageBreakdown : SFIODataObject
{
}

@property (nonatomic, strong) NSDictionary *ZonesToUsage;


@end
