//
// SFLink.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFItem.h"
#import "SFODataObject.h"


@interface SFLink : SFItem
{
}

/**
   Universal Reference Identifier for this Link object
 */
@property (nonatomic, strong) NSURL *Uri;


@end
