//
// SFMarketAnalytics.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFMarketAnalytics : SFODataObject
{
}

@property (nonatomic, strong) NSNumber *ConversionIndex;
@property (nonatomic, strong) NSNumber *ConversionIndex2;
@property (nonatomic, strong) NSNumber *LtvIndex;
@property (nonatomic, strong) NSNumber *PlanValue;


@end
