//
//  Autogenerated by a tool.
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

	
extern NSString * const kSFShareAccessRightTypeViewOnline;
	
extern NSString * const kSFShareAccessRightTypeIRM;
	
extern NSString * const kSFShareAccessRightTypeFullControl;
	
extern NSString * const kSFShareActionTypeLink;
	
extern NSString * const kSFShareActionTypeEmail;
	
extern NSString * const kSFBillingCycleMonthsMonth;
	
extern NSString * const kSFBillingCycleMonthsQuarter;
	
extern NSString * const kSFBillingCycleMonthsYear;
	
extern NSString * const kSFFreeTrialTypeGeneral;
	
extern NSString * const kSFFreeTrialTypeCreditCard;
	
extern NSString * const kSFFreeTrialTypeNoCreditCard;
	
extern NSString * const kSFFreeTrialTypeOutbound;
	
extern NSString * const kSFFreeTrialTypeTestDemo;
	
extern NSString * const kSFFreeTrialTypeCreditCardManualConversion;
	
extern NSString * const kSFFreeTrialTypeNoCreditCardSales;
	
extern NSString * const kSFFreeTrialTypePureNoCreditCard;
	
extern NSString * const kSFFreeTrialTypeEnterprise;
	
extern NSString * const kSFFreeTrialTypeOSDReferral;
	
extern NSString * const kSFFreeTrialTypePartner;
	
extern NSString * const kSFFreeTrialTypeFreemium;
	
extern NSString * const kSFDataCenterHosted;
	
extern NSString * const kSFDataCenterAmazon_US_VA;
	
extern NSString * const kSFDataCenterAmazon_US_CA;
	
extern NSString * const kSFDataCenterAmazon_EU_IE;
	
extern NSString * const kSFDataCenterAmazon_EU_IE_NoBackup;
	
extern NSString * const kSFDataCenterAmazon_AP_SG;
	
extern NSString * const kSFDataCenterAmazon_AP_JP;
	
extern NSString * const kSFDataCenterAmazon_US_OR;
	
extern NSString * const kSFDataCenterAmazon_SA_BR;
	
extern NSString * const kSFDataCenterAmazon_AU_SYD;
	
extern NSString * const kSFDataCenterAzure_US_East;
	
extern NSString * const kSFDataCenterAmazon_HIPAA_East;
	
extern NSString * const kSFDataCenterAmazon_HIPAA_West;
	
extern NSString * const kSFLimitingFactorNone;
	
extern NSString * const kSFLimitingFactorEmployees;
	
extern NSString * const kSFLimitingFactorStorageGB;
	
extern NSString * const kSFLimitingFactorBandwidthGB;
	
extern NSString * const kSFAddonFieldEmployees;
	
extern NSString * const kSFAddonFieldStorageGB;
	
extern NSString * const kSFAddonFieldBandwidthGB;
	
extern NSString * const kSFRepresentativeTypeAll;
	
extern NSString * const kSFRepresentativeTypeMasterUser;
	
extern NSString * const kSFRepresentativeTypeMasterAccountManager;
	
extern NSString * const kSFRepresentativeTypeMasterBranding;
	
extern NSString * const kSFRepresentativeTypeMasterDeveloper;
	
extern NSString * const kSFRepresentativeTypeMasterSales;
	
extern NSString * const kSFRepresentativeTypeAccountManager;
	
extern NSString * const kSFRepresentativeTypeBranding;
	
extern NSString * const kSFRepresentativeTypeDeveloper;
	
extern NSString * const kSFRepresentativeTypeSales;
	
extern NSString * const kSFRepresentativeTypeHR;
	
extern NSString * const kSFRepresentativeTypeMarketing;
	
extern NSString * const kSFRepresentativeTypeInternAccountManager;
	
extern NSString * const kSFRepresentativeTypeInternBranding;
	
extern NSString * const kSFRepresentativeTypeInternDeveloper;
	
extern NSString * const kSFRepresentativeTypeInternSales;
	
extern NSString * const kSFRepresentativeTypeDefault;
	
extern NSString * const kSFRepresentativeTypeAstronaut;
	
extern NSString * const kSFRepresentativeTypeEnterpriseSales;
	
extern NSString * const kSFRepRoleAccountManager;
	
extern NSString * const kSFRepRoleAccountServices;
	
extern NSString * const kSFRepRoleBranding;
	
extern NSString * const kSFRepRoleCustomerSupport;
	
extern NSString * const kSFRepRoleHR;
	
extern NSString * const kSFRepRoleImpersonation;
	
extern NSString * const kSFRepRoleInsideSales;
	
extern NSString * const kSFRepRoleInternBranding;
	
extern NSString * const kSFRepRoleInternDeveloper;
	
extern NSString * const kSFRepRoleMasterAccountManager;
	
extern NSString * const kSFRepRoleMasterBranding;
	
extern NSString * const kSFRepRoleMasterDeveloper;
	
extern NSString * const kSFRepRoleMasterSales;
	
extern NSString * const kSFRepRoleOutboundSales;
	
extern NSString * const kSFRepRoleSales;
	
extern NSString * const kSFRepRoleSeniorAccountManager;
	
extern NSString * const kSFRepRoleSuccessManager;
	
extern NSString * const kSFRepRoleInternalAppsDev;
	
extern NSString * const kSFRepRoleSupportManager;
	
extern NSString * const kSFRepRoleLevelISupport;
	
extern NSString * const kSFRepRoleLevelIISupport;
	
extern NSString * const kSFRepRoleLevelIIISupport;
	
extern NSString * const kSFRepRoleEngineering;
	
extern NSString * const kSFRepRoleManager;
	
extern NSString * const kSFRepRoleSalesDirector;
	
extern NSString * const kSFRepRoleInboundSalesManager;
	
extern NSString * const kSFRepRoleOutboundSalesManager;
	
extern NSString * const kSFRepRoleAccounting;
	
extern NSString * const kSFRepRoleResellersManager;
	
extern NSString * const kSFRepRoleTeamImpersonation;
	
extern NSString * const kSFRepRoleClientServicesManager;
	
extern NSString * const kSFRepRoleBrandingManager;
	
extern NSString * const kSFRepRoleOLMktg;
	
extern NSString * const kSFRepRoleExecTeam;
	
extern NSString * const kSFRepRoleOther;
	
extern NSString * const kSFRepRoleLoginAsSupport;
	
extern NSString * const kSFRepRoleEnterpriseSalesmanager;
	
extern NSString * const kSFRepRoleSSO;
	
extern NSString * const kSFRepRoleProjectManager;
	
extern NSString * const kSFRepRoleQA;
	
extern NSString * const kSFRepRoleTrialDispatcher;
	
extern NSString * const kSFRepRoleTrialDispatcherVerticals;
	
extern NSString * const kSFRepRoleReadOnly;
	
extern NSString * const kSFRepRoleAccountManagerAutoAssign;
	
extern NSString * const kSFRepRoleAccountProvisioning;
	
extern NSString * const kSFRepRoleCanDeleteAccounts;
	
extern NSString * const kSFRepRoleSupportTriage;
	
extern NSString * const kSFRepRoleOutboundCustomerCare;
	
extern NSString * const kSFRepRoleSalesEngineer;
	
extern NSString * const kSFRepRoleRelease;
	
extern NSString * const kSFRepRoleTechnicalServiceEngineer;
	
extern NSString * const kSFRepRoleIT;
	
extern NSString * const kSFRepRoleDatabase;
	
extern NSString * const kSFRepRoleBillingAdmin;
	
extern NSString * const kSFRepRoleSalesOps;
	
extern NSString * const kSFRepRoleOAuthClientKeyAdmin;
	
extern NSString * const kSFCloudStorageTypeNone;
	
extern NSString * const kSFCloudStorageTypeAmazon;
	
extern NSString * const kSFCloudStorageTypeAzure;
	
extern NSString * const kSFDatabaseLevelStandard;
	
extern NSString * const kSFDatabaseLevelEnterprise;
	
extern NSString * const kSFLockTypeSoftLock;
	
extern NSString * const kSFLockTypeHardLock;
	
extern NSString * const kSFLockTypeCoauthLock;
	
extern NSString * const kSFReportTypeAccess;
	
extern NSString * const kSFReportTypeActivity;
	
extern NSString * const kSFReportTypeStorage;
	
extern NSString * const kSFReportTypeMessaging;
	
extern NSString * const kSFReportTypeBandwidthDetail;
	
extern NSString * const kSFReportTypeBandwidthSummary;
	
extern NSString * const kSFReportTypeEncryptedEmail;
	
extern NSString * const kSFReportObjectTypeAccount;
	
extern NSString * const kSFReportObjectTypeFolder;
	
extern NSString * const kSFReportObjectTypeUser;
	
extern NSString * const kSFReportDateOptionSpecific;
	
extern NSString * const kSFReportDateOptionToday;
	
extern NSString * const kSFReportDateOptionYesterday;
	
extern NSString * const kSFReportDateOptionThisWeek;
	
extern NSString * const kSFReportDateOptionLastWeek;
	
extern NSString * const kSFReportDateOptionThisMonth;
	
extern NSString * const kSFReportDateOptionLastMonth;
	
extern NSString * const kSFReportDateOptionLast30Days;
	
extern NSString * const kSFReportRunFrequencyOnce;
	
extern NSString * const kSFReportRunFrequencyDaily;
	
extern NSString * const kSFReportRunFrequencyWeekly;
	
extern NSString * const kSFReportRunFrequencyMonthly;
	
extern NSString * const kSFReportRunStatusPending;
	
extern NSString * const kSFReportRunStatusRunning;
	
extern NSString * const kSFReportRunStatusSuccess;
	
extern NSString * const kSFReportRunStatusFailed;
	
extern NSString * const kSFTypeOfTourNoTour;
	
extern NSString * const kSFTypeOfTourWelcome;
	
extern NSString * const kSFTypeOfTourSync;
	
extern NSString * const kSFTypeOfTourWoolworthsLimited;
	
extern NSString * const kSFTypeOfTourRadiant;
	
extern NSString * const kSFTypeOfTourSuperUserAutoConvert;
	
extern NSString * const kSFTypeOfTourSuperUserManualConvert;
	
extern NSString * const kSFTypeOfTourNewFeature;
	
extern NSString * const kSFTypeOfTourNewEmployee;
	
extern NSString * const kSFTypeOfTourTFA;
	
extern NSString * const kSFTypeOfTourGetApp;
	
extern NSString * const kSFTypeOfTourScanSnap;
	
extern NSString * const kSFTypeOfTourCheckInCheckOut;
	
extern NSString * const kSFClientCapabilityHardLock;
	
extern NSString * const kSFVersioningDefault;
	
extern NSString * const kSFVersioningEnabled;
	
extern NSString * const kSFVersioningDisabled;
	
extern NSString * const kSFDocumentViewerPrintingDefault;
	
extern NSString * const kSFDocumentViewerPrintingEnabled;
	
extern NSString * const kSFDocumentViewerPrintingDisabled;
	
extern NSString * const kSFWatermarkedDownloadsDefault;
	
extern NSString * const kSFWatermarkedDownloadsEnabled;
	
extern NSString * const kSFWatermarkedDownloadsDisabled;
	
extern NSString * const kSFFolderOptionForcedSort;
	
extern NSString * const kSFFolderOptionForcedThumbnails;
	
extern NSString * const kSFFolderOptionEnableDisplayInline;
	
extern NSString * const kSFFolderOptionEnableDocViewerPrinting;
	
extern NSString * const kSFFolderOptionViewOnlyWatermarkText;
	
extern NSString * const kSFFolderOptionIsVersioned;
	
extern NSString * const kSFFolderOptionEnableWatermarkedDownloads;
	
extern NSString * const kSFFolderOptionMaxVersions;
	
extern NSString * const kSFAccountSubTypeNone;
	
extern NSString * const kSFAccountSubTypePartner;
	
extern NSString * const kSFAccountSubTypeTenant;
	
extern NSString * const kSFDlpStatusUnscanned;
	
extern NSString * const kSFDlpStatusScannedOK;
	
extern NSString * const kSFDlpStatusScannedRejected;
	
extern NSString * const kSFEditingPlatformMicrosoftOfficeOnline;
	
extern NSString * const kSFShareFileAccessRightsNoAccess;
	
extern NSString * const kSFShareFileAccessRightsView;
	
extern NSString * const kSFShareFileAccessRightsLightViewer;
	
extern NSString * const kSFShareFileAccessRightsPrint;
	
extern NSString * const kSFShareFileAccessRightsEdit;
	
extern NSString * const kSFShareFileAccessRightsFullControl;
	
extern NSString * const kSFShareFileAccessRightsCopyData;
	
extern NSString * const kSFShareFileAccessRightsScreenCapture;
	
extern NSString * const kSFShareFileAccessRightsMacro;
	
extern NSString * const kSFShareFileAccessRightsOfflineAccess;
	
extern NSString * const kSFShareFileAccessRightsRedistribute;
	
extern NSString * const kSFExceptionReasonUnspecified;
	
extern NSString * const kSFExceptionReasonFileTooLarge;
	
extern NSString * const kSFExceptionReasonQuotaExceeded;
	
extern NSString * const kSFExceptionReasonBadRequest;
	
extern NSString * const kSFExceptionReasonNotAuthenticated;
	
extern NSString * const kSFExceptionReasonNotAuthorized;
	
extern NSString * const kSFExceptionReasonConflict;
	
extern NSString * const kSFExceptionReasonDatabaseError;
	
extern NSString * const kSFExceptionReasonDlpViolation;
	
extern NSString * const kSFExceptionReasonFeatureDisabled;
	
extern NSString * const kSFExceptionReasonForbidden;
	
extern NSString * const kSFExceptionReasonNotAllowed;
	
extern NSString * const kSFExceptionReasonNotFound;
	
extern NSString * const kSFExceptionReasonThrottled;
	
extern NSString * const kSFExceptionReasonEmployeeLicensesExceeded;
	
extern NSString * const kSFExceptionReasonClientMustBeCreatedAsEmployee;
	
extern NSString * const kSFExceptionReasonVosPreviewNotAvailable;
	
extern NSString * const kSFExceptionReasonUnsupportedVosFileType;
	
extern NSString * const kSFExceptionReasonErrorGeneratingPreview;
	
extern NSString * const kSFExceptionReasonFileIsLocked;
	
extern NSString * const kSFExceptionReasonViewLimitReached;
	
extern NSString * const kSFExceptionReasonDownloadLimitReached;
	
extern NSString * const kSFExceptionReasonAlreadyActivatedToken;
	
extern NSString * const kSFExceptionReasonInvalidValidationCode;
	
extern NSString * const kSFExceptionReasonInvalidActivationToken;
	
extern NSString * const kSFExceptionReasonExpiredActivationToken;
	
extern NSString * const kSFExceptionReasonLoginWhitelistViolation;
	
extern NSString * const kSFExceptionReasonLoginBlacklistViolation;
	
extern NSString * const kSFExceptionReasonUpdateSecurityQuestionError;
	
extern NSString * const kSFExceptionReasonInvalidPassword;
	
extern NSString * const kSFExceptionReasonServiceUnavailable;
	
extern NSString * const kSFExceptionReasonUnsupportedVosWithImgFileType;
	
extern NSString * const kSFExceptionReasonEmailWhitelistViolation;
	
extern NSString * const kSFExceptionReasonEmailBlacklistViolation;
	
extern NSString * const kSFExceptionReasonIrmClassificationError;
	
extern NSString * const kSFExceptionReasonUnsupportedIrmFileType;
	
extern NSString * const kSFExceptionReasonIrmClassificationDisabled;
	
extern NSString * const kSFExceptionReasonIrmClassificationNotFound;
	
extern NSString * const kSFExceptionReasonDuplicateIrmClassificationName;
	
extern NSString * const kSFNotificationLocaleInvariant;
	
extern NSString * const kSFNotificationLocaleEnglish;
	
extern NSString * const kSFNotificationLocaleGerman;
	
extern NSString * const kSFNotificationLocaleSpanish;
	
extern NSString * const kSFNotificationLocaleFrench;
	
extern NSString * const kSFNotificationLocaleDutch;
	
extern NSString * const kSFNotificationLocaleChinese;
	
extern NSString * const kSFNotificationLocaleRussian;
	
extern NSString * const kSFNotificationLocaleJapanese;
	
extern NSString * const kSFNotificationLocaleKorean;
	
extern NSString * const kSFNotificationLocalePortuguese;
	
extern NSString * const kSFIntegrationProviderRightSignature;
	
extern NSString * const kSFIntegrationProviderRightSignature4;
	
extern NSString * const kSFIntegrationProviderDocumentApprovalWorkflow;
	
extern NSString * const kSFDocumentApprovalWorkflowActionShowDashboard;
	
extern NSString * const kSFDocumentApprovalWorkflowActionInitiateApproval;
	
extern NSString * const kSFDocumentApprovalWorkflowActionCollectFeedback;
	
extern NSString * const kSFESignatureDocumentStatusSentToProvider;
	
extern NSString * const kSFESignatureDocumentStatusSentForSignature;
	
extern NSString * const kSFESignatureDocumentStatusSigned;
	
extern NSString * const kSFESignatureDocumentStatusComplete;
	
extern NSString * const kSFMobileUserRoleSingleUser;
	
extern NSString * const kSFMobileUserRoleTeamUser;
	
extern NSString * const kSFMobileUserRoleTeamAdmin;
	
extern NSString * const kSFPlanAddonsStatusTrialNotStarted;
	
extern NSString * const kSFPlanAddonsStatusTrial;
	
extern NSString * const kSFPlanAddonsStatusTrialExpired;
	
extern NSString * const kSFPlanAddonsStatusPaid;
	
extern NSString * const kSFPlanAddonsStatusPaidExpired;
	
extern NSString * const kSFPlanAddonsStatusDisabled;
	
extern NSString * const kSFAppStoreiOS;
	
extern NSString * const kSFAppStoreAndroid;
	
extern NSString * const kSFAppStoreWeb;
	
extern NSString * const kSFOAuthClientPermissionsNotWanted;
	
extern NSString * const kSFOAuthClientPermissionsRequired;
	
extern NSString * const kSFOAuthClientPermissionsOptional;
	
extern NSString * const kSFOAuthStateInactive;
	
extern NSString * const kSFOAuthStateAuthorized;
	
extern NSString * const kSFOAuthStateRevoked;
	
extern NSString * const kSFAppCodes_None;
	
extern NSString * const kSFAppCodesAirWidget;
	
extern NSString * const kSFAppCodesSync2Win;
	
extern NSString * const kSFAppCodesSync2Mac;
	
extern NSString * const kSFAppCodesAirSyncWin;
	
extern NSString * const kSFAppCodesAirSyncMac;
	
extern NSString * const kSFAppCodesAirSyncMacLegacy;
	
extern NSString * const kSFAppCodesAirEntSync;
	
extern NSString * const kSFAppCodesSFCLI;
	
extern NSString * const kSFAppCodesOutlookPlugin;
	
extern NSString * const kSFAppCodesSFAndroid;
	
extern NSString * const kSFAppCodesSFAndroidPhone;
	
extern NSString * const kSFAppCodesSFAndroidTablet;
	
extern NSString * const kSFAppCodesSFiOS;
	
extern NSString * const kSFAppCodesSFiPad;
	
extern NSString * const kSFAppCodesSFiPhone;
	
extern NSString * const kSFAppCodesSFBlackberry;
	
extern NSString * const kSFAppCodesSFWinPhone;
	
extern NSString * const kSFAppCodesSFWinRT;
	
extern NSString * const kSFAppCodesDriveMapping;
	
extern NSString * const kSFAppCodesMobileSite;
	
extern NSString * const kSFAppCodesWebDav;
	
extern NSString * const kSFAppCodesFmd4Win;
	
extern NSString * const kSFAppCodesFmd4Mac;
	
extern NSString * const kSFAppCodesFmd;
	
extern NSString * const kSFAppCodesSFiPad_MDM;
	
extern NSString * const kSFAppCodesSFiPhone_MDM;
	
extern NSString * const kSFAppCodesSFiOS_MDM;
	
extern NSString * const kSFAppCodesSFAndroidPhone_MDM;
	
extern NSString * const kSFAppCodesSFAndroidTablet_MDM;
	
extern NSString * const kSFAppCodesSFAndroid_MDM;
	
extern NSString * const kSFAppCodesThirdParty;
	
extern NSString * const kSFAppCodesSF_FTP;
	
extern NSString * const kSFAppCodesSF_SFTP;
	
extern NSString * const kSFAppCodesSFWebApp;
	
extern NSString * const kSFAppCodesSFMarketing;
	
extern NSString * const kSFAppCodesShareConnect;
	
extern NSString * const kSFAppCodesShareConnectWeb;
	
extern NSString * const kSFAppCodesSFWindowsDesktop;
	
extern NSString * const kSFAppCodesApiDocumentation;
	
extern NSString * const kSFAppCodesSFQuickBooksOnline;
	
extern NSString * const kSFAppCodesSFScanSnap;
	
extern NSString * const kSFAppCodesSFPrintDriver;
	
extern NSString * const kSFAppCodesInternalApps;
	
extern NSString * const kSFAppCodesSFSonyDigitalPaper;
	
extern NSString * const kSFAppCodesSFAndroidChrome;
	
extern NSString * const kSFAppCodesCitrixLegal;
	
extern NSString * const kSFAppCodesRightSignature;
	
extern NSString * const kSFAppCodesMigrationTool;
	
extern NSString * const kSFAppCodesMSDirectToFile;
	
extern NSString * const kSFAppCodesImage32;
	
extern NSString * const kSFAppCodesDocumentApprovalWorkflow;
	
extern NSString * const kSFConnectorGroupKindCloud;
	
extern NSString * const kSFConnectorGroupKindZone;
	
extern NSString * const kSFConnectorGroupKindSDK;
	
extern NSString * const kSFConnectorGroupKindAgent;
	
extern NSString * const kSFPreviewPlatformWeb;
	
extern NSString * const kSFPreviewPlatformWebAndMobile;
	
extern NSString * const kSFPreviewPlatformMobile;
	
extern NSString * const kSFPreviewPlatformAll;
	
extern NSString * const kSFFileActionView;
	
extern NSString * const kSFFileActionEdit;
	
extern NSString * const kSFAccessControlFilterAllowDomains;
	
extern NSString * const kSFAccessControlFilterDisallowDomains;
	
extern NSString * const kSFUXModeClassic;
	
extern NSString * const kSFUXModeTabView;
	
extern NSString * const kSFVRootTypeAccount;
	
extern NSString * const kSFVRootTypeVirtual;
	
extern NSString * const kSFVRootTypeForcedVirtual;
	
extern NSString * const kSFVRootTypeClassicVirtual;
	
extern NSString * const kSFVRootTypeForcedClassicVirtual;
	
extern NSString * const kSFVRootTypeHome;
	
extern NSString * const kSFVRootTypeForcedDefault;
	
extern NSString * const kSFVRootTypeDefault;
	
extern NSString * const kSFAsyncOperationTypeCopy;
	
extern NSString * const kSFAsyncOperationTypeMove;
	
extern NSString * const kSFAsyncOperationTypeChangeZone;
	
extern NSString * const kSFAsyncOperationTypeScheduleChangeZone;
	
extern NSString * const kSFAsyncOperationTypeRecovery;
	
extern NSString * const kSFAsyncOperationTypeDelete;
	
extern NSString * const kSFAsyncOperationTypeDeletePermanent;
	
extern NSString * const kSFAsyncOperationTypeCloudConnectorCopy;
	
extern NSString * const kSFAsyncOperationTypeCloudConnectorFileCopy;
	
extern NSString * const kSFAsyncOperationTypeCloudConnectorMove;
	
extern NSString * const kSFAsyncOperationTypeCloudConnectorFileMove;
	
extern NSString * const kSFAsyncOperationStateCreated;
	
extern NSString * const kSFAsyncOperationStateScheduled;
	
extern NSString * const kSFAsyncOperationStateSuccess;
	
extern NSString * const kSFAsyncOperationStateFailure;
	
extern NSString * const kSFAsyncOperationStateCanceled;
	
extern NSString * const kSFCapabilityNameThumbnails;
	
extern NSString * const kSFCapabilityNameDocPreview;
	
extern NSString * const kSFCapabilityNameSearch;
	
extern NSString * const kSFCapabilityNameAdvancedSearch;
	
extern NSString * const kSFCapabilityNameSharing;
	
extern NSString * const kSFCapabilityNameAnonymousSharing;
	
extern NSString * const kSFCapabilityNameLastProgenyUpdateDate;
	
extern NSString * const kSFCapabilityNameDirectDownload;
	
extern NSString * const kSFCapabilityNameDirectUpload;
	
extern NSString * const kSFCapabilityNameCheckIn;
	
extern NSString * const kSFCapabilityNameCheckOut;
	
extern NSString * const kSFCapabilityNameFileVersioning;
	
extern NSString * const kSFCapabilityNameRecycleBin;
	
extern NSString * const kSFCapabilityNameFolderTemplates;
	
extern NSString * const kSFCapabilityNameVirusScan;
	
extern NSString * const kSFCapabilityNameItemLink;
	
extern NSString * const kSFCapabilityNameItemNote;
	
extern NSString * const kSFCapabilityNameItemDescription;
	
extern NSString * const kSFCapabilityNameVersionMax;
	
extern NSString * const kSFCapabilityNameVersionMin;
	
extern NSString * const kSFCapabilityNameFavorites;
	
extern NSString * const kSFCapabilityNameReusableItemId;
	
extern NSString * const kSFCapabilityNameStandardUploadRaw;
	
extern NSString * const kSFCapabilityNameStandardUploadForms;
	
extern NSString * const kSFCapabilityNameStreamedUploadRaw;
	
extern NSString * const kSFCapabilityNameStreamedUploadForms;
	
extern NSString * const kSFCapabilityNameThreadedUploadRaw;
	
extern NSString * const kSFCapabilityNameThreadedUploadForms;
	
extern NSString * const kSFCapabilityNameRightSignature;
	
extern NSString * const kSFCapabilityNameUploadWithRequestParams;
	
extern NSString * const kSFCapabilityNameSoftLock;
	
extern NSString * const kSFCapabilityNameHardLock;
	
extern NSString * const kSFCapabilityNameDownloadByStream;
	
extern NSString * const kSFCapabilityNameBulkDelete;
	
extern NSString * const kSFCapabilityNameBulkDownload;
	
extern NSString * const kSFCapabilityNameFolderDownload;
	
extern NSString * const kSFCapabilityNameFolderSend;
	
extern NSString * const kSFCapabilityNameSendByStream;
	
extern NSString * const kSFCapabilityNameSharingRequest;
	
extern NSString * const kSFCapabilityNameSharingSend;
	
extern NSString * const kSFCapabilityNameAnonymousSharingRequest;
	
extern NSString * const kSFCapabilityNameAnonymousSharingSend;
	
extern NSString * const kSFCapabilityNameCopy;
	
extern NSString * const kSFCapabilityNameMove;
	
extern NSString * const kSFCapabilityNameUnZipFileUploads;
	
extern NSString * const kSFCapabilityNameRightSignature4;
	
extern NSString * const kSFCapabilityNameDocumentApprovalWorkflow;
	
extern NSString * const kSFCapabilityNameShareAccessRight;
	
extern NSString * const kSFDeviceActionInitiatorRoleAccountAdmin;
	
extern NSString * const kSFDeviceActionInitiatorRoleDeviceOwner;
	
extern NSString * const kSFDeviceActionInitiatorRoleDeviceUser;
	
extern NSString * const kSFSFToolDriveMapping;
	
extern NSString * const kSFSFToolEnterpriseSync;
	
extern NSString * const kSFSFToolFTP;
	
extern NSString * const kSFSFToolOutlook;
	
extern NSString * const kSFSFToolSFCLI;
	
extern NSString * const kSFSFToolSFTP;
	
extern NSString * const kSFSFToolSMTP;
	
extern NSString * const kSFSFToolSync;
	
extern NSString * const kSFSFToolWebDAV;
	
extern NSString * const kSFSFToolWidget;
	
extern NSString * const kSFSFToolAndroidPhone;
	
extern NSString * const kSFSFToolAndroidTablet;
	
extern NSString * const kSFSFToolBlackberryPhone;
	
extern NSString * const kSFSFToolBlackberryTablet;
	
extern NSString * const kSFSFTooliPhone;
	
extern NSString * const kSFSFTooliPad;
	
extern NSString * const kSFSFToolReceiverAndroid;
	
extern NSString * const kSFSFToolReceiveriOS;
	
extern NSString * const kSFSFToolReceiverMac;
	
extern NSString * const kSFSFToolReceiverWindows;
	
extern NSString * const kSFSFToolWindowsPhone;
	
extern NSString * const kSFSFToolUnknown;
	
extern NSString * const kSFDeviceLogEntryActionOpenGeneric;
	
extern NSString * const kSFDeviceLogEntryActionOpenExternal;
	
extern NSString * const kSFDeviceLogEntryActionOpenPreview;
	
extern NSString * const kSFDeviceLogEntryActionShareSocial;
	
extern NSString * const kSFEnsEventTypeNone;
	
extern NSString * const kSFEnsEventTypeCreate;
	
extern NSString * const kSFEnsEventTypeUpdate;
	
extern NSString * const kSFEnsEventTypeDelete;
	
extern NSString * const kSFEnsEventTypeAll;
	
extern NSString * const kSFFileVirusStatusVirusWarning;
	
extern NSString * const kSFFileVirusStatusNotScanned;
	
extern NSString * const kSFFileVirusStatusClean;
	
extern NSString * const kSFPreviewStatusNone;
	
extern NSString * const kSFPreviewStatusHasThumb;
	
extern NSString * const kSFPreviewStatusHasPreview;
	
extern NSString * const kSFPreviewStatusCanImgThumb;
	
extern NSString * const kSFPreviewStatusCanDocThumb;
	
extern NSString * const kSFPreviewStatusCanDocPreview;
	
extern NSString * const kSFPreviewStatusRequiresPreview;
	
extern NSString * const kSFPreviewStatusProcessing;
	
extern NSString * const kSFPreviewStatusFailed;
	
extern NSString * const kSFItemActionDownload;
	
extern NSString * const kSFItemActionUpload;
	
extern NSString * const kSFItemActionView;
	
extern NSString * const kSFItemActionWatermarkDownload;
	
extern NSString * const kSFItemActionNote;
	
extern NSString * const kSFItemActionUrl;
	
extern NSString * const kSFItemActionDownloadESignature;
	
extern NSString * const kSFItemActionWOPI_View;
	
extern NSString * const kSFItemActionWOPI_Download;
	
extern NSString * const kSFItemActionUploadReceipt;
	
extern NSString * const kSFItemActionFileLock;
	
extern NSString * const kSFItemActionFileUnLock;
	
extern NSString * const kSFItemActionFileDiscardLock;
	
extern NSString * const kSFItemActionNone;
	
extern NSString * const kSFItemActionZipUpload;
	
extern NSString * const kSFItemActionItem_Delete;
	
extern NSString * const kSFItemActionItem_Edit;
	
extern NSString * const kSFItemActionItem_Restore;
	
extern NSString * const kSFItemActionMove;
	
extern NSString * const kSFItemActionNewFolder;
	
extern NSString * const kSFItemActionNewNote;
	
extern NSString * const kSFItemActionNewLink;
	
extern NSString * const kSFItemActionStreamLockCreate;
	
extern NSString * const kSFItemActionStreamLockDelete;
	
extern NSString * const kSFItemActionStreamLockUpdate;
	
extern NSString * const kSFItemActionStreamLockRelease;
	
extern NSString * const kSFItemActionDLP_Scan_Accept;
	
extern NSString * const kSFItemActionDLP_Scan_Reject;
	
extern NSString * const kSFItemActionDLP_Share_Allow;
	
extern NSString * const kSFItemActionDLP_Share_Deny;
	
extern NSString * const kSFItemActionDocument_View;
	
extern NSString * const kSFItemActionDocument_Edit;
	
extern NSString * const kSFItemActionItem_Archive;
	
extern NSString * const kSFItemOrderingModeDefault;
	
extern NSString * const kSFItemOrderingModeFoldersFirst;
	
extern NSString * const kSFTreeModeStandard;
	
extern NSString * const kSFTreeModeCopy;
	
extern NSString * const kSFTreeModeMove;
	
extern NSString * const kSFTreeModeSync;
	
extern NSString * const kSFTreeModeManage;
	
extern NSString * const kSFSortFieldUsersPreferences;
	
extern NSString * const kSFSortFieldName;
	
extern NSString * const kSFSortFieldFileSizeBytes;
	
extern NSString * const kSFSortFieldCreationDate;
	
extern NSString * const kSFSortFieldCreatorName;
	
extern NSString * const kSFSortFieldPath;
	
extern NSString * const kSFSortFieldType;
	
extern NSString * const kSFSortFieldNone;
	
extern NSString * const kSFSortDirectionNone;
	
extern NSString * const kSFSortDirectionAscending;
	
extern NSString * const kSFSortDirectionDescending;
	
extern NSString * const kSFPinLockTypeNone;
	
extern NSString * const kSFPinLockTypeUserSelected;
	
extern NSString * const kSFPinLockTypeNumeric;
	
extern NSString * const kSFPinLockTypeAlphanumeric;
	
extern NSString * const kSFODataObjectTypeComplexType;
	
extern NSString * const kSFODataObjectTypeEntity;
	
extern NSString * const kSFQueueStatusCreated;
	
extern NSString * const kSFQueueStatusScheduled;
	
extern NSString * const kSFQueueStatusSuccess;
	
extern NSString * const kSFQueueStatusFailed;
	
extern NSString * const kSFQueueStatusCanceled;
	
extern NSString * const kSFShareTypeRequest;
	
extern NSString * const kSFShareTypeSend;
	
extern NSString * const kSFShareTypeBoth;
	
extern NSString * const kSFShareSubTypeNone;
	
extern NSString * const kSFShareSubTypeEmail;
	
extern NSString * const kSFShareSubTypeConnector;
	
extern NSString * const kSFUploadMethodStandard;
	
extern NSString * const kSFUploadMethodStreamed;
	
extern NSString * const kSFUploadMethodThreaded;
	
extern NSString * const kSFUserRoleClient;
	
extern NSString * const kSFUserRoleEmployee;
	
extern NSString * const kSFUserRoleMasterAdmin;
	
extern NSString * const kSFUserRoleSuperUser;
	
extern NSString * const kSFUserRoleCanChangePassword;
	
extern NSString * const kSFUserRoleCanManageMySettings;
	
extern NSString * const kSFUserRoleCanUseFileBox;
	
extern NSString * const kSFUserRoleCanManageUsers;
	
extern NSString * const kSFUserRoleCanCreateFolders;
	
extern NSString * const kSFUserRoleCanUseDropBox;
	
extern NSString * const kSFUserRoleCanSelectFolderZone;
	
extern NSString * const kSFUserRoleCreateNetworkShareConnectors;
	
extern NSString * const kSFUserRoleCreateSharePointConnectors;
	
extern NSString * const kSFUserRoleCreateSharePointOnlineConnectors;
	
extern NSString * const kSFUserRoleCreateOneDriveConnectors;
	
extern NSString * const kSFUserRoleCreateExchangeConnectors;
	
extern NSString * const kSFUserRoleCreateBoxConnectors;
	
extern NSString * const kSFUserRoleCreateDropboxConnectors;
	
extern NSString * const kSFUserRoleCreateGoogleDriveConnectors;
	
extern NSString * const kSFUserRoleCreateOneDriveBusinessConnectors;
	
extern NSString * const kSFUserRoleAdminAccountPolicies;
	
extern NSString * const kSFUserRoleAdminBilling;
	
extern NSString * const kSFUserRoleAdminBranding;
	
extern NSString * const kSFUserRoleAdminChangeFolderPay;
	
extern NSString * const kSFUserRoleAdminChangePlan;
	
extern NSString * const kSFUserRoleAdminFileBoxAccess;
	
extern NSString * const kSFUserRoleAdminManageEmployees;
	
extern NSString * const kSFUserRoleAdminRemoteUploadForms;
	
extern NSString * const kSFUserRoleAdminReporting;
	
extern NSString * const kSFUserRoleAdminSharedDistGroups;
	
extern NSString * const kSFUserRoleAdminSharedAddressBook;
	
extern NSString * const kSFUserRoleAdminViewVdrAnalytics;
	
extern NSString * const kSFUserRoleAdminViewReceipts;
	
extern NSString * const kSFUserRoleAdminDelegate;
	
extern NSString * const kSFUserRoleAdminManageDropBox;
	
extern NSString * const kSFUserRoleAdminManageFolderTemplates;
	
extern NSString * const kSFUserRoleAdminEmailMessages;
	
extern NSString * const kSFUserRoleAdminSSO;
	
extern NSString * const kSFUserRoleAdminSuperGroup;
	
extern NSString * const kSFUserRoleAdminZones;
	
extern NSString * const kSFUserRoleAdminCreateSharedGroups;
	
extern NSString * const kSFUserRoleAdminArchivedSearch;
	
extern NSString * const kSFUserRoleAdminConnectors;
	
extern NSString * const kSFUserRoleAdminEmailArchiver;
	
extern NSString * const kSFUserRoleAdminCanAdministerCustomerAccount;
	
extern NSString * const kSFZoneTypePrivate;
	
extern NSString * const kSFZoneTypePublic;
	
extern NSString * const kSFZoneTypePrivateZeroKnowledge;
	
extern NSString * const kSFZoneTypeCitrixManaged;
	
extern NSString * const kSFZoneTypePrivateCitrixManaged;
	
extern NSString * const kSFZoneServiceNone;
	
extern NSString * const kSFZoneServiceStorageZone;
	
extern NSString * const kSFZoneServiceNetworkShareConnector;
	
extern NSString * const kSFZoneServiceSharepointConnector;
	
extern NSString * const kSFZoneServiceAzureStorageZone;
	
extern NSString * const kSFZoneServiceSharePointOnlineConnector;
	
extern NSString * const kSFZoneServiceBoxConnector;
	
extern NSString * const kSFZoneServiceDropboxConnector;
	
extern NSString * const kSFZoneServiceOneDriveConnector;
	
extern NSString * const kSFZoneServiceGoogleDriveConnector;
	
extern NSString * const kSFZoneServiceExchangeConnector;
	
extern NSString * const kSFZoneServiceGenericConnector;
	
extern NSString * const kSFZoneServiceOneDriveBusinessConnector;
	
extern NSString * const kSFZoneServiceShareConnectConnector;
	
extern NSString * const kSFZoneServicePreview;
	
extern NSString * const kSFZoneServiceHighConcurrency;
	
extern NSString * const kSFZoneServiceInformationRightsManagement;
