//
// SFNotifyUsersParams.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFNotifyUsersParams : SFODataObject
{
}

@property (nonatomic, strong) NSArray *UserIds;
@property (nonatomic, strong) NSString *CustomMessage;


@end
