//
// SFNote.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFNote.h"
#import "SFItem.h"
#import "SFODataObject.h"


@implementation SFNote

@end
