//
// SFODataFeed.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFODataFeed : SFODataObject
{
}

@property (nonatomic, strong) NSNumber *count;
@property (nonatomic, strong) NSArray *value;
@property (nonatomic, strong) NSString *nextLink;


@end
