//
// SFODataObject.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import <Foundation/Foundation.h>


@interface SFODataObject : NSObject
{
}

/**
   ODATA Metadata information about the model instance
 */
@property (nonatomic, strong) NSString *metadata;
@property (nonatomic, strong) NSString *type;
/**
   Object Identifier
 */
@property (nonatomic, strong) NSString *Id;
@property (nonatomic, strong) NSURL *url;
@property (nonatomic, strong) NSDictionary *Properties;

@property (nonatomic, strong) NSURL *MetadataBaseURI;
@property (nonatomic, strong) NSString *MetadataEntitySet;
@property (nonatomic, strong) NSNumber *MetadataAPIVersion;
@property (nonatomic, strong) NSString *MetadataProviderType;

@end
