//
// SFOutlookInformation.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"

@class SFOutlookInformationOptionString;
@class SFOutlookInformationOptionBool;
@class SFOutlookInformationOptionInt;

@interface SFOutlookInformation : SFODataObject
{
}

@property (nonatomic, strong) SFOutlookInformationOptionString *DownloadInfoLevel;
@property (nonatomic, strong) SFOutlookInformationOptionString *UploadInfoLevel;
@property (nonatomic, strong) SFOutlookInformationOptionBool *NotifyOnDownload;
@property (nonatomic, strong) SFOutlookInformationOptionBool *NotifyOnUpload;
@property (nonatomic, strong) SFOutlookInformationOptionInt *MaxDownloads;
@property (nonatomic, strong) SFOutlookInformationOptionString *LinkExpiration;
@property (nonatomic, strong) SFOutlookInformationOptionString *RequestText;
@property (nonatomic, strong) SFOutlookInformationOptionString *SendText;
@property (nonatomic, strong) SFOutlookInformationOptionString *BannerHTML;
@property (nonatomic, strong) SFOutlookInformationOptionBool *UseBanner;
@property (nonatomic, strong) SFOutlookInformationOptionBool *AutoConvert;
@property (nonatomic, strong) SFOutlookInformationOptionInt *ConvertAbove;
@property (nonatomic, strong) SFOutlookInformationOptionBool *AttachPaperclip;
@property (nonatomic, strong) SFOutlookInformationOptionString *EncryptedEmailRecipientVerification;
@property (nonatomic, strong) SFOutlookInformationOptionString *EncryptedEmailExpiration;
@property (nonatomic, strong) SFOutlookInformationOptionBool *EncryptedEmailNotifyOnRead;


@end
