//
// SFOutlookInformationOptionBool.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFOutlookInformationOptionBool.h"
#import "SFODataObject.h"


@implementation SFOutlookInformationOptionBool

@end
