//
// SFOutlookInformation.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFOutlookInformation.h"
#import "SFODataObject.h"

@class SFOutlookInformationOptionString;
@class SFOutlookInformationOptionBool;
@class SFOutlookInformationOptionInt;

@implementation SFOutlookInformation

@end
