//
// SFOutlookInformationOptionString.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFOutlookInformationOptionString : SFODataObject
{
}

@property (nonatomic, strong) NSNumber *Locked;
@property (nonatomic, strong) NSString *Value;


@end
