//
// SFPowerTools.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFPowerTools : SFODataObject
{
}

@property (nonatomic, strong) NSNumber *EnableDesktopToolsPage;
@property (nonatomic, strong) NSNumber *EnableMobileApps;
@property (nonatomic, strong) NSNumber *ShowMobileTools;


@end
