//
// SFPreviewPlatformInfo.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"

@class SFItemProtocolLink;

@interface SFPreviewPlatformInfo : SFODataObject
{
}

/**
   Indicates the Preview platform
 */
@property (nonatomic, strong) NSString *PreviewPlatform;
/**
   Indicates the ItemProtocolLink for this Preview platform
 */
@property (nonatomic, strong) SFItemProtocolLink *ItemProtocolLink;


@end
