//
// SFProductDefaults.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFProductDefaults.h"
#import "SFODataObject.h"


@implementation SFProductDefaults

@end
