//
// SFProductDefaults.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFProductDefaults : SFODataObject
{
}

@property (nonatomic, strong) NSString *ProductName;
@property (nonatomic, strong) NSString *DefaultWindowTitle;
@property (nonatomic, strong) NSString *TopLevelDomain;
@property (nonatomic, strong) NSString *APITopLevelDomain;
@property (nonatomic, strong) NSString *DefaultApiVersion;
@property (nonatomic, strong) NSString *DefaultSmtpServer;
@property (nonatomic, strong) NSString *NoReplyUserName;
@property (nonatomic, strong) NSString *NoReplyUserEmail;
@property (nonatomic, strong) NSString *SupportUserName;
@property (nonatomic, strong) NSString *SupportUserEmail;
@property (nonatomic, strong) NSString *DefaultEmailFooter;
@property (nonatomic, strong) NSString *DefaultEmailFooterHtml;
@property (nonatomic, strong) NSString *DefaultEmailFooterPlaintext;
@property (nonatomic, strong) NSString *DefaultEmailOverview;
@property (nonatomic, strong) NSString *SupportUserNotificationEmail;
@property (nonatomic, strong) NSString *SystemType;


@end
