//
// SFQueryPaging.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFQueryPaging.h"
#import "SFODataObject.h"


@implementation SFQueryPaging

@end
