//
// SFQuerySorting.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFQuerySorting.h"
#import "SFODataObject.h"


@implementation SFQuerySorting

@end
