//
// SFQuery.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFQuery : SFODataObject
{
}

/**
   Types of items to search for (ex "File", "Folder", etc.)
 */
@property (nonatomic, strong) NSArray *ItemTypes;
/**
   Parent id constraints on search results
 */
@property (nonatomic, strong) NSArray *ParentID;
/**
   Creator id constraints on search results
 */
@property (nonatomic, strong) NSArray *CreatorID;
/**
   Search term to search for
 */
@property (nonatomic, strong) NSString *SearchQuery;
/**
   Item creation date range constraint start date in UTC
 */
@property (nonatomic, strong) NSString *CreateStartDate;
/**
   Item creation date range constraint end date in UTC
 */
@property (nonatomic, strong) NSString *CreateEndDate;
/**
   Whether item content should be included in the search or not.
 */
@property (nonatomic, strong) NSNumber *ItemNameOnly;


@end
