//
// SFQuery.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFQuery.h"
#import "SFODataObject.h"


@implementation SFQuery

@end
