//
// SFReport.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFReport.h"
#import "SFODataObject.h"

@class SFItem;
@class SFUser;

@implementation SFReport

@end
