//
// SFRequireWebPopResult.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFRequireWebPopResult.h"
#import "SFODataObject.h"


@implementation SFRequireWebPopResult

@end
