//
// SFRemoteUploadRequestParams.h
// 
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFUploadRequestParams.h"
#import "SFODataObject.h"

@class SFContact;

@interface SFRemoteUploadRequestParams : SFUploadRequestParams
{

}

@property (nonatomic, strong) SFContact *Creator;


@end