//
// SFRequireWebPopResult.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFRequireWebPopResult : SFODataObject
{
}

@property (nonatomic, strong) NSNumber *RequireWebPop;


@end
