//
// SFReportRecord.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFReportRecord.h"
#import "SFODataObject.h"

@class SFReport;

@implementation SFReportRecord

@end
