//
// SFSearchQuery.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFSearchQuery.h"
#import "SFODataObject.h"

@class SFQuery;
@class SFQueryPaging;
@class SFQuerySorting;

@implementation SFSearchQuery

@end
