//
// SFSession.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"

@class SFPrincipal;
@class SFDeviceUser;

@interface SFSession : SFODataObject
{
}

@property (nonatomic, strong) SFPrincipal *Principal;
@property (nonatomic, strong) NSString *AuthenticationType;
@property (nonatomic, strong) NSString *OAuth2ClientName;
@property (nonatomic, strong) NSString *Tool;
@property (nonatomic, strong) NSString *Version;
@property (nonatomic, strong) NSString *ClientIPAddress;
@property (nonatomic, strong) NSNumber *IsAuthenticated;
@property (nonatomic, strong) NSString *Name;
@property (nonatomic, strong) SFDeviceUser *DeviceUser;


@end
