//
// SFService.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFService : SFODataObject
{
}

@property (nonatomic, strong) NSString *AddOnCode;
@property (nonatomic, strong) NSNumber *Licenses;


@end
