//
// SFServicesCollection.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFServicesCollection.h"
#import "SFODataObject.h"

@class SFAService;

@implementation SFServicesCollection

@end
