//
// SFSearchQuery.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"

@class SFQuery;
@class SFQueryPaging;
@class SFQuerySorting;

@interface SFSearchQuery : SFODataObject
{
}

/**
   Information about the query to run
 */
@property (nonatomic, strong) SFQuery *Query;
/**
   Paging info about the search results
 */
@property (nonatomic, strong) SFQueryPaging *Paging;
/**
   How the search results should be sorted
 */
@property (nonatomic, strong) SFQuerySorting *Sort;
/**
   Timeout for the search request in seconds
 */
@property (nonatomic, strong) NSNumber *TimeoutInSeconds;


@end
