//
// SFSession.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFSession.h"
#import "SFODataObject.h"

@class SFPrincipal;
@class SFDeviceUser;

@implementation SFSession

@end
