//
// SFShareAlias.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFShareAlias.h"
#import "SFODataObject.h"

@class SFUser;
@class SFShare;

@implementation SFShareAlias

@end
