//
// SFShare.m
// sfapiv3
// 
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFShare.h"
#import "SFODataObject.h"

@class SFItem;
@class SFUser;
@class SFZone;
@class SFRedirection;
@class SFShareSettings;
@class SFShareAccessRight;

@implementation SFShare

@end