//
// SFShareAccessRight.h
// 
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFShareAccessRight : SFODataObject
{

}

/**
Localized text for downstream clients to use for displaying options
*/
@property (nonatomic, strong) NSString *DisplayText;
/**
Share Access Right Type
*/
@property (nonatomic, strong) NSString *AccessRightType;


@end