//
// SFShareItemHistory.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFShareItemHistory : SFODataObject
{
}

@property (nonatomic, strong) NSString *Title;
@property (nonatomic, strong) NSString *Recipient;
@property (nonatomic, strong) NSString *ActivityType;
@property (nonatomic, strong) NSDate *DownloadDate;


@end
