//
// SFShareRequestParams.h
// 
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFShareRequestParams : SFODataObject
{

}

/**
The Folder Id for this Request. Has precedence over FolderPath
*/
@property (nonatomic, strong) NSString *FolderId;
/**
The path to the Folder for this Request
*/
@property (nonatomic, strong) NSString *FolderPath;
/**
List of emails to whom this Share should be sent
*/
@property (nonatomic, strong) NSArray *Emails;
/**
The subject of the Share email
*/
@property (nonatomic, strong) NSString *Subject;
/**
A message to be included in the Share email body
*/
@property (nonatomic, strong) NSString *Body;
/**
If true, the Share sender will be cc'd in the Share email
*/
@property (nonatomic, strong) NSNumber *CcSender;
/**
If true, recipients will need to login to access the Share
*/
@property (nonatomic, strong) NSNumber *RequireLogin;
/**
Number of days until access to this Share expires
*/
@property (nonatomic, strong) NSNumber *ExpirationDays;
/**
If true, the sender will receive an email notification when files are uploaded to the Share
*/
@property (nonatomic, strong) NSNumber *NotifyOnUpload;
/**
If true, the Share items can only be viewed but not downloaded. Not applicable for Request Shares
*/
@property (nonatomic, strong) NSNumber *IsViewOnly;


@end