//
// SFShareSendParams.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFShareSendParams.h"
#import "SFODataObject.h"

@class SFShareAccessRight;

@implementation SFShareSendParams

@end
