//
// SFShareSettings.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFShareSettings : SFODataObject
{
}

@property (nonatomic, strong) NSNumber *NotifyOnUse;


@end
