//
// SFShareAlias.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"

@class SFUser;
@class SFShare;

@interface SFShareAlias : SFODataObject
{
}

@property (nonatomic, strong) SFUser *User;
@property (nonatomic, strong) SFShare *Share;
@property (nonatomic, strong) NSString *Email;
@property (nonatomic, strong) NSNumber *Downloads;
@property (nonatomic, strong) NSNumber *IsConsumed;
@property (nonatomic, strong) NSNumber *IsArchived;
@property (nonatomic, strong) NSNumber *IsRead;
/**
   Uri to access the share through the Web portal
 */
@property (nonatomic, strong) NSURL *Uri;


@end
