//
// SFSSOAccountProvider.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFSSOAccountProvider.h"
#import "SFODataObject.h"

@class SFAccount;

@implementation SFSSOAccountProvider

@end
