//
// SFSSOInfoEntry.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFSSOInfoEntry : SFODataObject
{
}

@property (nonatomic, strong) NSString *Key;
@property (nonatomic, strong) NSString *Value;


@end
