//
// SFSSOInfo.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFSSOInfo : SFODataObject
{
}

@property (nonatomic, strong) NSArray *Info;
@property (nonatomic, strong) NSString *AppControlPlane;
@property (nonatomic, strong) NSString *ApiControlPlane;


@end
