//
// SFSSOAccountProvider.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"

@class SFAccount;

@interface SFSSOAccountProvider : SFODataObject
{
}

@property (nonatomic, strong) NSString *LogoutUrl;
@property (nonatomic, strong) NSString *LoginUrl;
@property (nonatomic, strong) NSString *IPRestrictions;
@property (nonatomic, strong) NSNumber *ForceSSO;
@property (nonatomic, strong) NSString *Certificate;
@property (nonatomic, strong) SFAccount *Account;
@property (nonatomic, strong) NSString *EntityID;
@property (nonatomic, strong) NSString *SFEntityID;
@property (nonatomic, strong) NSString *SSOProvidersToAccountsID;
@property (nonatomic, strong) NSString *SPInitatedAuthContext;
@property (nonatomic, strong) NSString *SPInitatedAuthMethod;
@property (nonatomic, strong) NSNumber *UseWebAuthentication;
@property (nonatomic, strong) NSNumber *IsActive;
@property (nonatomic, strong) NSNumber *IsDefault;
@property (nonatomic, strong) NSString *ProviderID;
@property (nonatomic, strong) NSNumber *DebugMode;
@property (nonatomic, strong) NSNumber *LenientSignatures;


@end
