//
// SFStorageCenter.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFStorageCenter.h"
#import "SFODataObject.h"

@class SFZone;

@implementation SFStorageCenter

@end
