//
// SFSymbolicLink.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFFolder.h"
#import "SFODataObject.h"

@class SFConnectorGroup;

@interface SFSymbolicLink : SFFolder
{
}

@property (nonatomic, strong) NSURL *Link;
@property (nonatomic, strong) SFConnectorGroup *ConnectorGroup;


@end
