//
// SFToolInformation.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFToolInformation : SFODataObject
{
}

@property (nonatomic, strong) NSString *ToolName;
@property (nonatomic, strong) NSString *Version;


@end
