//
// SFUploadSpecification.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFUploadSpecification.h"
#import "SFODataObject.h"


@implementation SFUploadSpecification

@end
