//
// SFUserPreferences.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFUserPreferences : SFODataObject
{
}

@property (nonatomic, strong) NSNumber *EnableFlashUpload;
@property (nonatomic, strong) NSNumber *EnableJavaUpload;
@property (nonatomic, strong) NSNumber *EnableJavaDownload;
@property (nonatomic, strong) NSNumber *RememberCustomMessages;
@property (nonatomic, strong) NSNumber *RequireLoginByDefault;
@property (nonatomic, strong) NSNumber *NotifyOnUploadByDefault;
@property (nonatomic, strong) NSNumber *NotifyOnDownloadByDefault;
@property (nonatomic, strong) NSNumber *CanResetPassword;
@property (nonatomic, strong) NSNumber *CanViewMySettings;
@property (nonatomic, strong) NSNumber *IsSharedUserAccount;
@property (nonatomic, strong) NSString *TimeZone;
@property (nonatomic, strong) NSString *DaylightSavingMode;
@property (nonatomic, strong) NSNumber *TimeZoneOffset;
@property (nonatomic, strong) NSNumber *TimeZoneOffsetMins;
@property (nonatomic, strong) NSNumber *DisplayUserMessage;
@property (nonatomic, strong) NSString *UserMessageCode;
@property (nonatomic, strong) NSNumber *NotificationInterval;
@property (nonatomic, strong) NSString *ShowTutorial;
@property (nonatomic, strong) NSNumber *EnableToolOverride;
@property (nonatomic, strong) NSNumber *IsResetSecurityQuestionRequired;
@property (nonatomic, strong) NSString *TimeFormat;
@property (nonatomic, strong) NSString *LongTimeFormat;
@property (nonatomic, strong) NSString *DateFormat;
@property (nonatomic, strong) NSNumber *EnableShareConnect;
@property (nonatomic, strong) NSNumber *ReceiveBouncedEmailNotifications;
@property (nonatomic, strong) NSNumber *EnablePromotions;
@property (nonatomic, strong) NSString *UserNotificationLocale;


@end
