//
// SFUserUsage.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFUserUsage : SFODataObject
{
}

@property (nonatomic, strong) NSNumber *EmployeeMax;
@property (nonatomic, strong) NSNumber *EmployeeCount;
@property (nonatomic, strong) NSNumber *ClientCount;


@end
