//
// SFUserInfo.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFUserInfo.h"
#import "SFODataObject.h"

@class SFPlanFeatures;

@implementation SFUserInfo

@end
