//
// SFUserInfo.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"

@class SFPlanFeatures;

@interface SFUserInfo : SFODataObject
{
}

@property (nonatomic, strong) NSString *CompanyName;
@property (nonatomic, strong) NSString *PlanName;
@property (nonatomic, strong) SFPlanFeatures *PlanFeatures;
@property (nonatomic, strong) NSString *ApplicationUrl;
@property (nonatomic, strong) NSString *StorageCenterUrl;


@end
