//
// SFUser.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFUser.h"
#import "SFPrincipal.h"
#import "SFODataObject.h"

@class SFAccount;
@class SFZone;
@class SFUserPreferences;
@class SFUserSecurity;
@class SFFolder;
@class SFUserInfo;

@implementation SFUser

@end
