//
// SFUser.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFPrincipal.h"
#import "SFODataObject.h"

@class SFAccount;
@class SFZone;
@class SFUserPreferences;
@class SFUserSecurity;
@class SFFolder;
@class SFUserInfo;

@interface SFUser : SFPrincipal
{
}

@property (nonatomic, strong) SFAccount *Account;
@property (nonatomic, strong) NSString *Company;
@property (nonatomic, strong) NSNumber *TotalSharedFiles;
@property (nonatomic, strong) NSNumber *Contacted;
@property (nonatomic, strong) NSString *FullName;
@property (nonatomic, strong) NSString *ReferredBy;
@property (nonatomic, strong) NSArray *Notifications;
@property (nonatomic, strong) SFZone *DefaultZone;
@property (nonatomic, strong) NSString *FirstName;
@property (nonatomic, strong) NSString *LastName;
@property (nonatomic, strong) NSDate *DateCreated;
@property (nonatomic, strong) NSString *FullNameShort;
@property (nonatomic, strong) NSArray *Emails;
@property (nonatomic, strong) NSNumber *IsConfirmed;
@property (nonatomic, strong) NSString *Password;
@property (nonatomic, strong) SFUserPreferences *Preferences;
@property (nonatomic, strong) SFUserSecurity *Security;
@property (nonatomic, strong) NSArray *FavoriteFolders;
@property (nonatomic, strong) SFFolder *HomeFolder;
@property (nonatomic, strong) NSArray *Devices;
@property (nonatomic, strong) NSArray *Integrations;
@property (nonatomic, strong) SFFolder *VirtualRoot;
@property (nonatomic, strong) NSArray *Roles;
@property (nonatomic, strong) SFUserInfo *Info;
@property (nonatomic, strong) NSString *AffiliatedPartnerUserId;


@end
