//
// SFUserConfirmRequirement.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"

@class SFUser;

@interface SFUserConfirmRequirement : SFODataObject
{
}

@property (nonatomic, strong) NSString *AuthenticationId;
@property (nonatomic, strong) NSNumber *IsProbableSAMLOnlyUser;
@property (nonatomic, strong) NSNumber *IsADLinked;
@property (nonatomic, strong) NSString *ADUserName;
@property (nonatomic, strong) NSString *TempPassword;
@property (nonatomic, strong) SFUser *User;


@end
