//
// SFZoneUsageBreakdown.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataObject.h"


@interface SFZoneUsageBreakdown : SFODataObject
{
}

@property (nonatomic, strong) NSDictionary *ZonesToUsage;


@end
