//
// SFZone.m
// sfapiv3
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFZone.h"
#import "SFPrincipal.h"
#import "SFODataObject.h"

@class SFAccount;

@implementation SFZone

@end
