//
// SFZone.h
//
// Autogenerated by a tool
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFPrincipal.h"
#import "SFODataObject.h"

@class SFAccount;

@interface SFZone : SFPrincipal
{
}

@property (nonatomic, strong) NSString *Secret;
@property (nonatomic, strong) NSString *ZoneType;
@property (nonatomic, strong) SFAccount *Account;
@property (nonatomic, strong) NSNumber *HeartBeatTolerance;
@property (nonatomic, strong) NSNumber *PingBackInterval;
@property (nonatomic, strong) NSString *Version;
@property (nonatomic, strong) NSString *ZoneServices;
@property (nonatomic, strong) NSNumber *IsHIPAAZone;
@property (nonatomic, strong) NSNumber *IsMultiTenant;
@property (nonatomic, strong) NSArray *StorageCenters;


@end
