//
//  SFAccessControlsEntity.m
//
//  Autogenerated by a tool.
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFHttpMethodConstants.h"
#import "SFEntityConstants.h"
#import "SFAccessControlsEntity.h"
#import "SFODataEntityBase.h"
#import "SFAccessControl.h"
#import "SFAccessControlsBulkParams.h"
#import "SFAccessControlBulkResult.h"
#import "SFAccessControlsCloneParams.h"
#import "SFNotifyUsersParams.h"


@implementation SFAccessControlsEntity
- (SFApiQuery *)getWithUrl:(NSURL *)url {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    sfApiQuery.responseClass = [SFAccessControl class];
    sfApiQuery.isODataFeed = NO;
    
    [sfApiQuery setFrom:kSFEntities_AccessControls];
    [sfApiQuery addIds:url];
    [sfApiQuery setHttpMethod:kSFHttpMethodGET];
    return sfApiQuery;
}

- (SFApiQuery *)getByItemWithUrl:(NSURL *)url {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    sfApiQuery.responseClass = [SFAccessControl class];
    sfApiQuery.isODataFeed = YES;
    
    [sfApiQuery setFrom:kSFEntities_Items];
    [sfApiQuery setAction:@"AccessControls"];
    [sfApiQuery addIds:url];
    [sfApiQuery setHttpMethod:kSFHttpMethodGET];
    return sfApiQuery;
}

- (SFApiQuery *)createByItemWithUrl:(NSURL *)url accessControl:(SFAccessControl *)accessControl message:(NSString *)message recursive:(NSNumber *)recursive andSendDefaultNotification:(NSNumber *)sendDefaultNotification {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    sfApiQuery.responseClass = [SFAccessControl class];
    sfApiQuery.isODataFeed = NO;
    
    [sfApiQuery setFrom:kSFEntities_Items];
    [sfApiQuery setAction:@"AccessControls"];
    [sfApiQuery addIds:url];
    [sfApiQuery addQueryString:@"recursive" withValue:recursive];
    [sfApiQuery addQueryString:@"sendDefaultNotification" withValue:sendDefaultNotification];
    [accessControl setProperties:@{
         @"Message" : message,
     }];
    [sfApiQuery setBody:accessControl];
    [sfApiQuery setHttpMethod:kSFHttpMethodPOST];
    return sfApiQuery;
}

- (SFApiQuery *)updateByItemWithUrl:(NSURL *)url accessControl:(SFAccessControl *)accessControl andRecursive:(NSNumber *)recursive {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    sfApiQuery.responseClass = [SFAccessControl class];
    sfApiQuery.isODataFeed = NO;
    
    [sfApiQuery setFrom:kSFEntities_Items];
    [sfApiQuery setAction:@"AccessControls"];
    [sfApiQuery addIds:url];
    [sfApiQuery addQueryString:@"recursive" withValue:recursive];
    [sfApiQuery setBody:accessControl];
    [sfApiQuery setHttpMethod:kSFHttpMethodPATCH];
    return sfApiQuery;
}

- (SFApiQuery *)deleteWithUrl:(NSURL *)url {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    
    [sfApiQuery setFrom:kSFEntities_AccessControls];
    [sfApiQuery addIds:url];
    [sfApiQuery setHttpMethod:kSFHttpMethodDELETE];
    return sfApiQuery;
}

- (SFApiQuery *)bulkSetWithUrl:(NSURL *)url andBulkParams:(SFAccessControlsBulkParams *)bulkParams {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    sfApiQuery.responseClass = [SFAccessControlBulkResult class];
    sfApiQuery.isODataFeed = NO;
    
    [sfApiQuery setFrom:kSFEntities_Items];
    [sfApiQuery setAction:@"AccessControls"];
    [sfApiQuery addIds:url];
    [sfApiQuery addSubAction:@"BulkSet"];
    [sfApiQuery setBody:bulkParams];
    [sfApiQuery setHttpMethod:kSFHttpMethodPOST];
    return sfApiQuery;
}

- (SFApiQuery *)bulkSetForPrincipalWithBulkParams:(SFAccessControlsBulkParams *)bulkParams andPrincipalId:(NSString *)principalId {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    sfApiQuery.responseClass = [SFAccessControlBulkResult class];
    sfApiQuery.isODataFeed = NO;
    
    [sfApiQuery setFrom:kSFEntities_AccessControls];
    [sfApiQuery setAction:@"BulkSetForPrincipal"];
    [sfApiQuery addQueryString:@"principalId" withValue:principalId];
    [sfApiQuery setBody:bulkParams];
    [sfApiQuery setHttpMethod:kSFHttpMethodPOST];
    return sfApiQuery;
}

- (SFApiQuery *)cloneWithAccessControlsCloneParams:(SFAccessControlsCloneParams *)accessControlsCloneParams {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    sfApiQuery.responseClass = [SFAccessControlBulkResult class];
    sfApiQuery.isODataFeed = NO;
    
    [sfApiQuery setFrom:kSFEntities_AccessControls];
    [sfApiQuery setAction:@"Clone"];
    [sfApiQuery setBody:accessControlsCloneParams];
    [sfApiQuery setHttpMethod:kSFHttpMethodPOST];
    return sfApiQuery;
}

- (SFApiQuery *)bulkDeleteWithFolderUrl:(NSURL *)folderUrl andPrincipalIds:(NSArray *)principalIds {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    
    [sfApiQuery setFrom:kSFEntities_Items];
    [sfApiQuery setAction:@"AccessControls"];
    [sfApiQuery addIds:folderUrl];
    [sfApiQuery addSubAction:@"BulkDelete"];
    [sfApiQuery setBody:principalIds];
    [sfApiQuery setHttpMethod:kSFHttpMethodPOST];
    return sfApiQuery;
}

- (SFApiQuery *)bulkDeleteForPrincipalWithFolderIds:(NSArray *)folderIds andPrincipalId:(NSString *)principalId {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    
    [sfApiQuery setFrom:kSFEntities_AccessControls];
    [sfApiQuery setAction:@"BulkDeleteForPrincipal"];
    [sfApiQuery addQueryString:@"principalId" withValue:principalId];
    [sfApiQuery setBody:folderIds];
    [sfApiQuery setHttpMethod:kSFHttpMethodPOST];
    return sfApiQuery;
}

- (SFApiQuery *)notifyUsersWithFolderUrl:(NSURL *)folderUrl andNotifyUsersParams:(SFNotifyUsersParams *)notifyUsersParams {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    
    [sfApiQuery setFrom:kSFEntities_Items];
    [sfApiQuery setAction:@"AccessControls"];
    [sfApiQuery addIds:folderUrl];
    [sfApiQuery addSubAction:@"NotifyUsers"];
    [sfApiQuery setBody:notifyUsersParams];
    [sfApiQuery setHttpMethod:kSFHttpMethodPOST];
    return sfApiQuery;
}

@end
