//
//  Autogenerated by a tool.
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFConnectorGroupsEntity.h"
#import "SFRemoteUploadsEntity.h"
#import "SFReportsEntity.h"
#import "SFFolderTemplatesEntity.h"
#import "SFAccessControlsEntity.h"
#import "SFAccountsEntity.h"
#import "SFAsyncOperationsEntity.h"
#import "SFCapabilitiesEntity.h"
#import "SFFavoriteFoldersEntity.h"
#import "SFGroupsEntity.h"
#import "SFItemsEntity.h"
#import "SFMetadataEntity.h"
#import "SFSessionsEntity.h"
#import "SFSharesEntity.h"
#import "SFStorageCentersEntity.h"
#import "SFUsersEntity.h"
#import "SFZonesEntity.h"
