//
//  SFFolderTemplatesEntity.m
//
//  Autogenerated by a tool.
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFHttpMethodConstants.h"
#import "SFEntityConstants.h"
#import "SFFolderTemplatesEntity.h"
#import "SFODataEntityBase.h"
#import "SFFolderTemplate.h"


@implementation SFFolderTemplatesEntity
-(SFApiQuery*)get
{
	SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
	sfApiQuery.responseClass = [SFFolderTemplate class];
	sfApiQuery.isODataFeed = YES;

	[sfApiQuery setFrom:kSFEntities_FolderTemplates];
	[sfApiQuery setHttpMethod:kSFHttpMethodGET];
	return sfApiQuery;
}

-(SFApiQuery*)getWithUrl:(NSURL*)url
{
	SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
	sfApiQuery.responseClass = [SFFolderTemplate class];
	sfApiQuery.isODataFeed = NO;

	[sfApiQuery setFrom:kSFEntities_FolderTemplates];
	[sfApiQuery addIds:url];
	[sfApiQuery setHttpMethod:kSFHttpMethodGET];
	return sfApiQuery;
}

-(SFApiQuery*)createWithSfTemplate:(SFFolderTemplate*)sfTemplate
{
	SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
	sfApiQuery.responseClass = [SFFolderTemplate class];
	sfApiQuery.isODataFeed = NO;

	[sfApiQuery setFrom:kSFEntities_FolderTemplates];
	[sfApiQuery setBody:sfTemplate];
	[sfApiQuery setHttpMethod:kSFHttpMethodPOST];
	return sfApiQuery;
}

-(SFApiQuery*)updateWithSfTemplate:(SFFolderTemplate*)sfTemplate
{
	SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
	sfApiQuery.responseClass = [SFFolderTemplate class];
	sfApiQuery.isODataFeed = NO;

	[sfApiQuery setFrom:kSFEntities_FolderTemplates];
	[sfApiQuery setBody:sfTemplate];
	[sfApiQuery setHttpMethod:kSFHttpMethodPATCH];
	return sfApiQuery;
}

-(SFApiQuery*)deleteWithUrl:(NSURL*)url
{
	SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];

	[sfApiQuery setFrom:kSFEntities_FolderTemplates];
	[sfApiQuery addIds:url];
	[sfApiQuery setHttpMethod:kSFHttpMethodDELETE];
	return sfApiQuery;
}

@end