//
//  SFFolderTemplatesEntity.h
//
//  Autogenerated by a tool.
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataEntityBase.h"

@class SFFolderTemplate;

@interface SFFolderTemplatesEntity : SFODataEntityBase
{

}

/**
@abstract Get Folder Templates for Current Account
Returns all folder templates for the current account.@return Folder templates for current account
*/
-(SFApiQuery*)get;
-(SFApiQuery*)getWithUrl:(NSURL*)url;

/**
@abstract Create Folder Template
@description
{
"Name": "Client Folder",
"Description": "For all client folders created in 2014 or after"
"Items": [
{
"Name": "Folder 1",
"Items": [
{
"Name": "Subfolder1"
}
]
},
{
"Name": "Folder 2"
}
]
Creates a new folder template.@return The created folder template
*/
-(SFApiQuery*)createWithSfTemplate:(SFFolderTemplate*)sfTemplate;

/**
@abstract Update Folder Template
@description
{
"Name": "Client Folder",
"Description": "For all client folders created in 2014 or after",
"Items": [
{
"Name": "A new folder",
"Items": [
{
"TemplateId": "ft-12345-abdef-abdef-12345-abdef",
"Name": "A new subfolder"
}
]
},
{
"Id": "fti-xxxxx-xxxxx-xxxxx-xxxxx",
"Name": "An existing folder with a different name"
}
]
}
Updates an existing folder template@return The updated folder template
*/
-(SFApiQuery*)updateWithSfTemplate:(SFFolderTemplate*)sfTemplate;

/**
@abstract Delete Folder Template
Removes a folder template	
@param id 	
*/
-(SFApiQuery*)deleteWithUrl:(NSURL*)url;
@end