//
//  SFIAccessControlsEntity.m
//
//  Autogenerated by a tool.
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIHttpMethodConstants.h"
#import "SFIEntityConstants.h"
#import "SFIAccessControlsEntity.h"
#import "SFIODataEntityBase.h"
#import "SFIAccessControl.h"
#import "SFIAccessControlsBulkParams.h"
#import "SFIAccessControlBulkResult.h"
#import "SFIAccessControlsCloneParams.h"
#import "SFINotifyUsersParams.h"


@implementation SFIAccessControlsEntity
- (SFApiQuery *)getWithUrl:(NSURL *)url {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    sfApiQuery.responseClass = [SFIAccessControl class];
    sfApiQuery.isODataFeed = NO;
    
    [sfApiQuery setFrom:kSFEntities_AccessControls];
    [sfApiQuery addIds:url];
    [sfApiQuery setHttpMethod:kSFHttpMethodGET];
    return sfApiQuery;
}

- (SFApiQuery *)getByItemWithUrl:(NSURL *)url {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    sfApiQuery.responseClass = [SFIAccessControl class];
    sfApiQuery.isODataFeed = YES;
    
    [sfApiQuery setFrom:kSFEntities_Items];
    [sfApiQuery setAction:@"AccessControls"];
    [sfApiQuery addIds:url];
    [sfApiQuery setHttpMethod:kSFHttpMethodGET];
    return sfApiQuery;
}

- (SFApiQuery *)createByItemWithUrl:(NSURL *)url accessControl:(SFIAccessControl *)accessControl message:(NSString *)message recursive:(NSNumber *)recursive andSendDefaultNotification:(NSNumber *)sendDefaultNotification {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    sfApiQuery.responseClass = [SFIAccessControl class];
    sfApiQuery.isODataFeed = NO;
    
    [sfApiQuery setFrom:kSFEntities_Items];
    [sfApiQuery setAction:@"AccessControls"];
    [sfApiQuery addIds:url];
    [sfApiQuery addQueryString:@"recursive" withValue:recursive];
    [sfApiQuery addQueryString:@"sendDefaultNotification" withValue:sendDefaultNotification];
    [accessControl setProperties:@{
         @"Message" : message,
     }];
    [sfApiQuery setBody:accessControl];
    [sfApiQuery setHttpMethod:kSFHttpMethodPOST];
    return sfApiQuery;
}

- (SFApiQuery *)updateByItemWithUrl:(NSURL *)url accessControl:(SFIAccessControl *)accessControl andRecursive:(NSNumber *)recursive {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    sfApiQuery.responseClass = [SFIAccessControl class];
    sfApiQuery.isODataFeed = NO;
    
    [sfApiQuery setFrom:kSFEntities_Items];
    [sfApiQuery setAction:@"AccessControls"];
    [sfApiQuery addIds:url];
    [sfApiQuery addQueryString:@"recursive" withValue:recursive];
    [sfApiQuery setBody:accessControl];
    [sfApiQuery setHttpMethod:kSFHttpMethodPATCH];
    return sfApiQuery;
}

- (SFApiQuery *)deleteWithUrl:(NSURL *)url {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    
    [sfApiQuery setFrom:kSFEntities_AccessControls];
    [sfApiQuery addIds:url];
    [sfApiQuery setHttpMethod:kSFHttpMethodDELETE];
    return sfApiQuery;
}

- (SFApiQuery *)bulkSetWithUrl:(NSURL *)url andBulkParams:(SFIAccessControlsBulkParams *)bulkParams {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    sfApiQuery.responseClass = [SFIAccessControlBulkResult class];
    sfApiQuery.isODataFeed = NO;
    
    [sfApiQuery setFrom:kSFEntities_Items];
    [sfApiQuery setAction:@"AccessControls"];
    [sfApiQuery addIds:url];
    [sfApiQuery addSubAction:@"BulkSet"];
    [sfApiQuery setBody:bulkParams];
    [sfApiQuery setHttpMethod:kSFHttpMethodPOST];
    return sfApiQuery;
}

- (SFApiQuery *)bulkSetForPrincipalWithBulkParams:(SFIAccessControlsBulkParams *)bulkParams andPrincipalId:(NSString *)principalId {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    sfApiQuery.responseClass = [SFIAccessControlBulkResult class];
    sfApiQuery.isODataFeed = NO;
    
    [sfApiQuery setFrom:kSFEntities_AccessControls];
    [sfApiQuery setAction:@"BulkSetForPrincipal"];
    [sfApiQuery addQueryString:@"principalId" withValue:principalId];
    [sfApiQuery setBody:bulkParams];
    [sfApiQuery setHttpMethod:kSFHttpMethodPOST];
    return sfApiQuery;
}

- (SFApiQuery *)cloneWithAccessControlsCloneParams:(SFIAccessControlsCloneParams *)accessControlsCloneParams {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    sfApiQuery.responseClass = [SFIAccessControlBulkResult class];
    sfApiQuery.isODataFeed = NO;
    
    [sfApiQuery setFrom:kSFEntities_AccessControls];
    [sfApiQuery setAction:@"Clone"];
    [sfApiQuery setBody:accessControlsCloneParams];
    [sfApiQuery setHttpMethod:kSFHttpMethodPOST];
    return sfApiQuery;
}

- (SFApiQuery *)bulkDeleteWithFolderUrl:(NSURL *)folderUrl andPrincipalIds:(NSArray *)principalIds {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    
    [sfApiQuery setFrom:kSFEntities_Items];
    [sfApiQuery setAction:@"AccessControls"];
    [sfApiQuery addIds:folderUrl];
    [sfApiQuery addSubAction:@"BulkDelete"];
    [sfApiQuery setBody:principalIds];
    [sfApiQuery setHttpMethod:kSFHttpMethodPOST];
    return sfApiQuery;
}

- (SFApiQuery *)bulkDeleteForPrincipalWithFolderIds:(NSArray *)folderIds andPrincipalId:(NSString *)principalId {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    
    [sfApiQuery setFrom:kSFEntities_AccessControls];
    [sfApiQuery setAction:@"BulkDeleteForPrincipal"];
    [sfApiQuery addQueryString:@"principalId" withValue:principalId];
    [sfApiQuery setBody:folderIds];
    [sfApiQuery setHttpMethod:kSFHttpMethodPOST];
    return sfApiQuery;
}

- (SFApiQuery *)notifyUsersWithFolderUrl:(NSURL *)folderUrl andNotifyUsersParams:(SFINotifyUsersParams *)notifyUsersParams {
    SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
    
    [sfApiQuery setFrom:kSFEntities_Items];
    [sfApiQuery setAction:@"AccessControls"];
    [sfApiQuery addIds:folderUrl];
    [sfApiQuery addSubAction:@"NotifyUsers"];
    [sfApiQuery setBody:notifyUsersParams];
    [sfApiQuery setHttpMethod:kSFHttpMethodPOST];
    return sfApiQuery;
}

@end
