//
//  SFICapabilitiesEntity.h
//
//  Autogenerated by a tool.
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataEntityBase.h"


@interface SFICapabilitiesEntity : SFIODataEntityBase
{
}

/**
   @abstract Get List of Capabilities
   Retrieves the capability list of a given provider.The URL for ShareFile API is of the form Domain/Provider/Version/EntityThe Domain is the server presenting the provider - typically sharefile.com,but can be any other when using Storage Zones. The Provider represent the kind of data storage connected by the API. Examplesare 'sf' for ShareFile; 'cifs' for CIFS; and 'sp' for SharePoint. Other providersmay be created, clients must not assume any particular string.Version specifies the API version - currently at V3. Any backward incompatiblechanges will be performed on a different version identifier, to avoid breakingexisting clients.The Capability document is used to indicate to clients that certain featuresare not available on a given provider - allowing the client to suppress UX controlsand avoid "Not Implemented" exceptions to the end-user.*/
- (SFApiQuery *)get;
@end
