//
//  Autogenerated by a tool.
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIConnectorGroupsEntity.h"
#import "SFIRemoteUploadsEntity.h"
#import "SFIReportsEntity.h"
#import "SFIFolderTemplatesEntity.h"
#import "SFIAccessControlsEntity.h"
#import "SFIAccountsEntity.h"
#import "SFIAsyncOperationsEntity.h"
#import "SFICapabilitiesEntity.h"
#import "SFIFavoriteFoldersEntity.h"
#import "SFIGroupsEntity.h"
#import "SFIItemsEntity.h"
#import "SFIMetadataEntity.h"
#import "SFISessionsEntity.h"
#import "SFISharesEntity.h"
#import "SFIStorageCentersEntity.h"
#import "SFIUsersEntity.h"
#import "SFIZonesEntity.h"
