//
//  SFIFolderTemplatesEntity.m
//
//  Autogenerated by a tool.
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIHttpMethodConstants.h"
#import "SFIEntityConstants.h"
#import "SFIFolderTemplatesEntity.h"
#import "SFIODataEntityBase.h"
#import "SFIFolderTemplate.h"


@implementation SFIFolderTemplatesEntity
-(SFApiQuery*)get
{
	SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
	sfApiQuery.responseClass = [SFIFolderTemplate class];
	sfApiQuery.isODataFeed = YES;

	[sfApiQuery setFrom:kSFEntities_FolderTemplates];
	[sfApiQuery setHttpMethod:kSFHttpMethodGET];
	return sfApiQuery;
}

-(SFApiQuery*)getWithUrl:(NSURL*)url
{
	SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
	sfApiQuery.responseClass = [SFIFolderTemplate class];
	sfApiQuery.isODataFeed = NO;

	[sfApiQuery setFrom:kSFEntities_FolderTemplates];
	[sfApiQuery addIds:url];
	[sfApiQuery setHttpMethod:kSFHttpMethodGET];
	return sfApiQuery;
}

-(SFApiQuery*)createWithSfTemplate:(SFIFolderTemplate*)sfTemplate
{
	SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
	sfApiQuery.responseClass = [SFIFolderTemplate class];
	sfApiQuery.isODataFeed = NO;

	[sfApiQuery setFrom:kSFEntities_FolderTemplates];
	[sfApiQuery setBody:sfTemplate];
	[sfApiQuery setHttpMethod:kSFHttpMethodPOST];
	return sfApiQuery;
}

-(SFApiQuery*)updateWithSfTemplate:(SFIFolderTemplate*)sfTemplate
{
	SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];
	sfApiQuery.responseClass = [SFIFolderTemplate class];
	sfApiQuery.isODataFeed = NO;

	[sfApiQuery setFrom:kSFEntities_FolderTemplates];
	[sfApiQuery setBody:sfTemplate];
	[sfApiQuery setHttpMethod:kSFHttpMethodPATCH];
	return sfApiQuery;
}

-(SFApiQuery*)deleteWithUrl:(NSURL*)url
{
	SFApiQuery *sfApiQuery = [[SFApiQuery alloc] initWithClient:self.client];

	[sfApiQuery setFrom:kSFEntities_FolderTemplates];
	[sfApiQuery addIds:url];
	[sfApiQuery setHttpMethod:kSFHttpMethodDELETE];
	return sfApiQuery;
}

@end
