//
//  SFIGroupsEntity.h
//
//  Autogenerated by a tool.
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFIODataEntityBase.h"

@class SFIGroup;

@interface SFIGroupsEntity : SFIODataEntityBase
{
}

/**
   @abstract Get Group List
   Retrieves all Distribution Groups this user has permissions to View in this account@return a list of Groups this user has access to
 */
- (SFApiQuery *)get;

/**
   @abstract Get Group By ID
   Retrives a single Group by id
   @param id
   @return A single Group object
 */
- (SFApiQuery *)getWithUrl:(NSURL *)url;

/**
   @abstract Delete Group
   Removes a single Group by id
   @param id
 */
- (SFApiQuery *)deleteWithUrl:(NSURL *)url;

/**
   @abstract Create Group
   @description
   {
   "Name":"Name",
   "IsShared":true,
   "Contacts":[{"Email":"user.one@domain.com"},{"Email":"user.two@domain.com"}]
   }
   Creates a new group. The Post body must include the specification of the group.
   @param group
   @return the new group instance
 */
- (SFApiQuery *)createWithGroup:(SFIGroup *)group;

/**
   @abstract Update Group
   @description
   {
   "Name":"Name",
   "IsShared":true,
   }
   Updates an existing group.This operation will ignore the provided clients list. Use the \Contacts navigation link toadd/remove elements from a group
   @param id
   @param group
   @return the modified group object
 */
- (SFApiQuery *)updateWithUrl:(NSURL *)url andGroup:(SFIGroup *)group;

/**
   @abstract Get Group Contacts
   Retrieves the Contacts navigation property of a Group
   @param id
   @return A feed of Contacts representing the members of the Group
 */
- (SFApiQuery *)getContactsWithUrl:(NSURL *)url;

/**
   @abstract Add Contacts to Group
   @description
   [{"Email":"user.one@domain.com"},{"Id":"abcd"}]
   Adds a list of contacts to a groupThe contact list may contain either contact ID (same as User ID) or Email.
   @param id
   @param contacts
   @return The updated list of contacts for this group
 */
- (SFApiQuery *)createContactsWithUrl:(NSURL *)url andContacts:(NSArray *)contacts;

/**
   @abstract Remove Contacts from Group
   @description
   [{"Email":"user.one@domain.com"},{"Id":"abcd"}]
   Removes contacts from a groupThe contact list may contain either contact ID (same as User ID) or Email.This method will ignore missing references in the provided list - i.e., if an email in the contactslist is not present in the group, it will be ignored.The method will not enforce that ID and Email match inside a single Contact instance: Id will belooked up first, then Email.
   @param id
   @param contacts
   @return The updated list of contacts for this group
 */
- (SFApiQuery *)deleteContactsWithUrl:(NSURL *)url andContacts:(NSArray *)contacts;
@end
