//
//  SFRemoteUploadsEntity.h
//
//  Autogenerated by a tool.
//  Copyright (c) 2016 Citrix ShareFile. All rights reserved.
//

#import "SFODataEntityBase.h"

@class SFRemoteUploadRequestParams;
@class SFRemoteUpload;

@interface SFRemoteUploadsEntity : SFODataEntityBase
{

}
-(SFApiQuery*)get;
-(SFApiQuery*)getPublic;
-(SFApiQuery*)getWithUrl:(NSURL*)url;
-(SFApiQuery*)upload2WithUrl:(NSURL*)url uploadParams:(SFRemoteUploadRequestParams*)uploadParams userId:(NSString*)userId andExpirationDays:(NSNumber*)expirationDays;
-(SFApiQuery*)createWithRemoteUpload:(SFRemoteUpload*)remoteUpload;
-(SFApiQuery*)updateWithRemoteUpload:(SFRemoteUpload*)remoteUpload;
-(SFApiQuery*)deleteWithId:(NSString*)Id;
-(SFApiQuery*)getUsers;
-(SFApiQuery*)validateRemoteUploadUserWithId:(NSString*)Id andEmail:(NSString*)email;
@end